/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.Company;
import com.krawler.common.admin.CostCenter;
import com.krawler.common.admin.KWLCurrency;
import com.krawler.common.admin.User;
import java.util.Date;
import java.util.Set;

/**
 *
 * @author krawler-user
 */
public class JournalEntry implements Comparable<JournalEntry> {

    private String ID;
    private String entryNumber;
    private boolean autoGenerated;
    private Date entryDate;
    private String memo;
    private Company company;
    private KWLCurrency currency;
    private Set<JournalEntryDetail> details;
    private double externalCurrencyRate;
    private boolean deleted;
    private boolean eliminateflag;
    private boolean intercompanyflag;
    private boolean optimizedflag;//true if this entry is added in jedetail_optimized table
    private Long createdOn;
    private String isInventory;
    private CostCenter costcenter;
    private String reverseJournalEntry;
    private String badDebtSeqNumber;
    private boolean isReverseJE;
    private Long templatepermcode;
    private int pendingapproval;
    private int isReval;
    private boolean badDebtJE;
    private boolean taxAdjustmentJE;
    private int typeValue;//1 = Normal, 2= Party, 3= Fund Transfer, 4= Rounding Off, 0= others 
    private int gstrType;//   ref Constants.GSTRJETYPE
    private int partlyJeEntryWithCnDn;
    private AccJECustomData accBillInvCustomData;
    private int istemplate;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private String revalInvoiceId; //For mainting relation to the invoice. 
    private RepeatedJE repeateJE;
    private JournalEntry parentJE;
    private Cheque cheque;
    private int approvestatuslevel;
    private User createdby;
	private double gstCurrencyRate;//Only used if the country is Singapore and the base currency is not SGD.
    private boolean chequeprinted;
    private MasterItem paidTo;
    private PaymentMethod paymentMethod;
    private double paymentcurrencytopaymentmethodcurrencyrate;
    private boolean ismulticurrencypaymentje;
    private String customer;
    private boolean isOneTimeReverse;
    private boolean isexchangegainslossje;
    private boolean draft; // set true if SI is saved as draft
    private boolean isDishonouredCheque;
    private String transactionId; // Used to store transaction id 
    private int transactionModuleid; // Used to store transaction module id 
    private boolean toIncludeInGSTReport; // Default false.  Ticket - 17298
    private boolean isFromPOS; // Is JE generated from POS App for cashout entry
    private boolean isFromEclaim; // Is JE generated from Eclaim side
    private BankReconcilationDraft reconciliationDraft;
    private String itcTransactionIds;   // Used for ITC type JE which will be created against ITC Reversed PI and Asset Aquired PI.

    public String getItcTransactionIds() {
        return itcTransactionIds;
    }

    public void setItcTransactionIds(String itcTransactionIds) {
        this.itcTransactionIds = itcTransactionIds;
    }

    public boolean isIsFromEclaim() {
        return isFromEclaim;
    }

    public void setIsFromEclaim(boolean isFromEclaim) {
        this.isFromEclaim = isFromEclaim;
    }
    
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public boolean isIsDishonouredCheque() {
        return isDishonouredCheque;
    }

    public boolean getIsDishonouredCheque() {
        return isDishonouredCheque;
    }
    
    public void setIsDishonouredCheque(boolean isDishonouredCheque) {
        this.isDishonouredCheque = isDishonouredCheque;
    }
    
    public boolean isIsOneTimeReverse() {
        return isOneTimeReverse;
    }

    public void setIsOneTimeReverse(boolean isOneTimeReverse) {
        this.isOneTimeReverse = isOneTimeReverse;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }
    
    public MasterItem getPaidTo() {
        return paidTo;
    }

    public void setPaidTo(MasterItem paidTo) {
        this.paidTo = paidTo;
    }
   

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public boolean isChequeprinted() {
        return chequeprinted;
    }

    public void setChequeprinted(boolean chequeprinted) {
        this.chequeprinted = chequeprinted;
    }

    public JournalEntry() {
        super();
        this.approvestatuslevel = 11;
    }
    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public int getIstemplate() {
        return istemplate;
    }

    public void setIstemplate(int istemplate) {
        this.istemplate = istemplate;
    }

    public AccJECustomData getAccBillInvCustomData() {
        return accBillInvCustomData;
    }

    public void setAccBillInvCustomData(AccJECustomData accBillInvCustomData) {
        this.accBillInvCustomData = accBillInvCustomData;
    }

    public String getID() {
        return ID;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public String getIsInventory() {
        return isInventory;
    }

    public void setIsInventory(String isInventory) {
        this.isInventory = isInventory;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getEntryNumber() {
        return entryNumber;
    }

    public void setEntryNumber(String entryNumber) {
        this.entryNumber = entryNumber;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Date getEntryDate() {
        return entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Set<JournalEntryDetail> getDetails() {
        return details;
    }

    public void setDetails(Set<JournalEntryDetail> details) {
        this.details = details;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public boolean isEliminateflag() {
        return eliminateflag;
    }

    public void setEliminateflag(boolean eliminateflag) {
        this.eliminateflag = eliminateflag;
    }

    public boolean isIntercompanyflag() {
        return intercompanyflag;
    }

    public void setIntercompanyflag(boolean intercompanyflag) {
        this.intercompanyflag = intercompanyflag;
    }

    public boolean isOptimizedflag() {
        return optimizedflag;
    }

    public void setOptimizedflag(boolean optimizedflag) {
        this.optimizedflag = optimizedflag;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public CostCenter getCostcenter() {
        return costcenter;
    }

    public void setCostcenter(CostCenter costcenter) {
        this.costcenter = costcenter;
    }
     public String getBadDebtSeqNumber() {
        return badDebtSeqNumber;
    }

    public void setBadDebtSeqNumber(String badDebtSeqNumber) {
        this.badDebtSeqNumber = badDebtSeqNumber;
    }

    @Override
    public int compareTo(JournalEntry o) {
        int result = 0;

        if (this.getCreatedOn() < o.getCreatedOn()) {
            result = 1;
        } else if (this.getCreatedOn() > o.getCreatedOn()) {
            result = -1;
        } else {
            result = 0;
        }

        return result;
    }

    public boolean isIsReverseJE() {
        return isReverseJE;
    }

    public void setIsReverseJE(boolean isReverseJE) {
        this.isReverseJE = isReverseJE;
    }

    public JournalEntry getParentJE() {
        return parentJE;
    }

    public void setParentJE(JournalEntry parentJE) {
        this.parentJE = parentJE;
    }

    public RepeatedJE getRepeateJE() {
        return repeateJE;
    }

    public void setRepeateJE(RepeatedJE repeateJE) {
        this.repeateJE = repeateJE;
    }

    public String getReverseJournalEntry() {
        return reverseJournalEntry;
    }

    public void setReverseJournalEntry(String reverseJournalEntry) {
        this.reverseJournalEntry = reverseJournalEntry;
    }

    public Long getTemplatepermcode() {
        return templatepermcode;
    }

    public void setTemplatepermcode(Long templatepermcode) {
        this.templatepermcode = templatepermcode;
    }

    public int getPendingapproval() {
        return pendingapproval;
    }

    public void setPendingapproval(int pendingapproval) {
        this.pendingapproval = pendingapproval;
    }

    public int getIsReval() {
        return isReval;
    }

    public void setIsReval(int isReval) {
        this.isReval = isReval;
    }

    public int getTypeValue() {
        return typeValue;
    }

    public void setTypeValue(int typeValue) {
        this.typeValue = typeValue;
    }

    public String getRevalInvoiceId() {
        return revalInvoiceId;
    }

    public void setRevalInvoiceId(String revalInvoiceId) {
        this.revalInvoiceId = revalInvoiceId;
    }

    public int getPartlyJeEntryWithCnDn() {
        return partlyJeEntryWithCnDn;
    }

    public void setPartlyJeEntryWithCnDn(int partlyJeEntryWithCnDn) {
        this.partlyJeEntryWithCnDn = partlyJeEntryWithCnDn;
    }

    public Cheque getCheque() {
        return cheque;
    }

    public void setCheque(Cheque cheque) {
        this.cheque = cheque;
    }
    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }

    public boolean isTaxAdjustmentJE() {
        return taxAdjustmentJE;
    }

    public void setTaxAdjustmentJE(boolean taxAdjustmentJE) {
        this.taxAdjustmentJE = taxAdjustmentJE;
    }

    public boolean isBadDebtJE() {
        return badDebtJE;
    }

    public void setBadDebtJE(boolean badDebtJE) {
        this.badDebtJE = badDebtJE;
    }
    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public double getGstCurrencyRate() {
        return gstCurrencyRate;
    }

    public void setGstCurrencyRate(double gstCurrencyRate) {
        this.gstCurrencyRate = gstCurrencyRate;
    }
    public double getPaymentcurrencytopaymentmethodcurrencyrate() {
        return paymentcurrencytopaymentmethodcurrencyrate;
    }

    public void setPaymentcurrencytopaymentmethodcurrencyrate(double paymentcurrencytopaymentmethodcurrencyrate) {
        this.paymentcurrencytopaymentmethodcurrencyrate = paymentcurrencytopaymentmethodcurrencyrate;
    }

    public boolean isIsmulticurrencypaymentje() {
        return ismulticurrencypaymentje;
    }

    public void setIsmulticurrencypaymentje(boolean ismulticurrencypaymentje) {
        this.ismulticurrencypaymentje = ismulticurrencypaymentje;
    }

    public boolean isIsexchangegainslossje() {
        return isexchangegainslossje;
    }
    
    public void setIsexchangegainslossje(boolean isexchangegainslossje) {
        this.isexchangegainslossje = isexchangegainslossje;
    }
    
    public boolean isDraft() {
        return draft;
    }

    public void setDraft(boolean draft) {
        this.draft = draft;
    }

    public String getTransactionId() {
        return transactionId;
}

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public int getTransactionModuleid() {
        return transactionModuleid;
    }

    public void setTransactionModuleid(int transactionModuleid) {
        this.transactionModuleid = transactionModuleid;
    }

    public boolean isToIncludeInGSTReport() {
        return toIncludeInGSTReport;
    }

    public void setToIncludeInGSTReport(boolean toIncludeInGSTReport) {
        this.toIncludeInGSTReport = toIncludeInGSTReport;
    }

    public boolean isIsFromPOS() {
        return isFromPOS;
    }

    public void setIsFromPOS(boolean isFromPOS) {
        this.isFromPOS = isFromPOS;
    }
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }

    public int getGstrType() {
        return gstrType;
    }

    public void setGstrType(int gstrType) {
        this.gstrType = gstrType;
    }

    public BankReconcilationDraft getReconciliationDraft() {
        return reconciliationDraft;
    }

    public void setReconciliationDraft(BankReconcilationDraft reconciliationDraft) {
        this.reconciliationDraft = reconciliationDraft;
    }
    
}
