/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import java.util.Date;
import java.util.Set;

public class BillingGoodsReceipt {

    private String ID;
    private String billingGoodsReceiptNumber;
    private boolean autoGenerated;
    private String billFrom;
    private String shipFrom;
    private Date dueDate;
    private Date shipDate;
    private String memo;
    private Discount discount;
    private JournalEntry journalEntry;
    private Set<BillingGoodsReceiptDetail> rows;
    private JournalEntryDetail vendorEntry;
    private JournalEntryDetail shipEntry;
    private JournalEntryDetail otherEntry;
    private JournalEntryDetail taxEntry;
    private ExchangeRateDetails exchangeRateDetail;
    private double externalCurrencyRate;
    private Company company;
    private KWLCurrency currency;
    private boolean deleted;
    private Tax tax;
    private Vendor vendor;
    private String shipvia;
    private String fob;
    private int pendingapproval;
    private Projreport_Template templateid;
    private boolean favourite;
    private User approver;
    private int approvallevel;
    private int istemplate;
    private String postText;
    private String billTo;
    private String shipTo;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private RepeatedInvoices repeateInvoice;
    
    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public String getShipTo() {
        return shipTo;
    }

    public void setShipTo(String shipTo) {
        this.shipTo = shipTo;
    }

    public int getIstemplate() {
        return istemplate;
    }

    public void setIstemplate(int istemplate) {
        this.istemplate = istemplate;
    }

    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public int getApprovallevel() {
        return approvallevel;
    }

    public void setApprovallevel(int approvallevel) {
        this.approvallevel = approvallevel;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Discount getDiscount() {
        return discount;
    }

    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public JournalEntryDetail getOtherEntry() {
        return otherEntry;
    }

    public void setOtherEntry(JournalEntryDetail otherEntry) {
        this.otherEntry = otherEntry;
    }

    public Date getShipDate() {
        return shipDate;
    }

    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    public JournalEntryDetail getShipEntry() {
        return shipEntry;
    }

    public void setShipEntry(JournalEntryDetail shipEntry) {
        this.shipEntry = shipEntry;
    }

    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }

    public JournalEntryDetail getTaxEntry() {
        return taxEntry;
    }

    public void setTaxEntry(JournalEntryDetail taxEntry) {
        this.taxEntry = taxEntry;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public ExchangeRateDetails getExchangeRateDetail() {
        return exchangeRateDetail;
    }

    public void setExchangeRateDetail(ExchangeRateDetails exchangeRateDetail) {
        this.exchangeRateDetail = exchangeRateDetail;
    }

    public String getBillFrom() {
        return billFrom;
    }

    public void setBillFrom(String billFrom) {
        this.billFrom = billFrom;
    }

    public String getBillingGoodsReceiptNumber() {
        return billingGoodsReceiptNumber;
    }

    public void setBillingGoodsReceiptNumber(String billingGoodsReceiptNumber) {
        this.billingGoodsReceiptNumber = billingGoodsReceiptNumber;
    }

    public Set<BillingGoodsReceiptDetail> getRows() {
        return rows;
    }

    public void setRows(Set<BillingGoodsReceiptDetail> rows) {
        this.rows = rows;
    }

    public String getShipFrom() {
        return shipFrom;
    }

    public void setShipFrom(String shipFrom) {
        this.shipFrom = shipFrom;
    }

    public JournalEntryDetail getVendorEntry() {
        return vendorEntry;
    }

    public void setVendorEntry(JournalEntryDetail vendorEntry) {
        this.vendorEntry = vendorEntry;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public String getFob() {
        return fob;
    }

    public void setFob(String fob) {
        this.fob = fob;
    }

    public String getShipvia() {
        return shipvia;
    }

    public void setShipvia(String shipvia) {
        this.shipvia = shipvia;
    }

    public int getPendingapproval() {
        return pendingapproval;
    }

    public void setPendingapproval(int pendingapproval) {
        this.pendingapproval = pendingapproval;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public User getApprover() {
        return approver;
    }

    public void setApprover(User approver) {
        this.approver = approver;
    }

    public String getPostText() {
        return postText;
    }

    public void setPostText(String postText) {
        this.postText = postText;
    }

    public RepeatedInvoices getRepeateInvoice() {
        return repeateInvoice;
    }

    public void setRepeateInvoice(RepeatedInvoices repeateInvoice) {
        this.repeateInvoice = repeateInvoice;
    }
    
}
