/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.Company;
import java.util.Date;
/**
 *
 * @author krawler
 */
public class DealerExciseDetails {
    
    private String id;
    private String RG23DEntryNumber;
    private String SupplierRG23DEntry;
    private String AssessableValue;
    private String PLARG23DEntry;
    private String ManuAssessableValue;
    private Company company;
    private SequenceFormat seqformat;
    private GoodsReceiptDetail goodsreceiptdetails;
    private int seqnumber;//Only to store integer part of sequence format
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private boolean autoGenerated;
    private String invoicenoManufacture;
    private Date invoiceDateManufacture;

    public String getAssessableValue() {
        return AssessableValue;
    }

    public void setAssessableValue(String AssessableValue) {
        this.AssessableValue = AssessableValue;
    }

    public String getManuAssessableValue() {
        return ManuAssessableValue;
    }

    public void setManuAssessableValue(String ManuAssessableValue) {
        this.ManuAssessableValue = ManuAssessableValue;
    }

    public String getPLARG23DEntry() {
        return PLARG23DEntry;
    }

    public void setPLARG23DEntry(String PLARG23DEntry) {
        this.PLARG23DEntry = PLARG23DEntry;
    }

    public String getRG23DEntryNumber() {
        return RG23DEntryNumber;
    }

    public void setRG23DEntryNumber(String RG23DEntryNumber) {
        this.RG23DEntryNumber = RG23DEntryNumber;
    }

    public String getSupplierRG23DEntry() {
        return SupplierRG23DEntry;
    }

    public void setSupplierRG23DEntry(String SupplierRG23DEntry) {
        this.SupplierRG23DEntry = SupplierRG23DEntry;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }

    public GoodsReceiptDetail getGoodsreceiptdetails() {
        return goodsreceiptdetails;
    }

    public void setGoodsreceiptdetails(GoodsReceiptDetail goodsreceiptdetails) {
        this.goodsreceiptdetails = goodsreceiptdetails;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }
    
    public Date getInvoiceDateManufacture() {
        return invoiceDateManufacture;
    }

    public void setInvoiceDateManufacture(Date invoiceDateManufacture) {
        this.invoiceDateManufacture = invoiceDateManufacture;
    }

    public String getInvoicenoManufacture() {
        return invoicenoManufacture;
    }

    public void setInvoicenoManufacture(String invoicenoManufacture) {
        this.invoicenoManufacture = invoicenoManufacture;
    }
}
