/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import java.util.Date;
import java.util.Set;

/**
 *
 * @author krawler
 */
public class GoodsReceiptOrder {

    private String ID;
    private String goodsReceiptOrderNumber;
    private boolean autoGenerated;
    private Date orderDate;
    private Date shipdate;
    private Vendor vendor;
    private String memo;
    private Set<GoodsReceiptOrderDetails> rows;
    private Company company;
    private boolean deleted;
    private CostCenter costcenter;
    private String shipvia;
    private boolean fixedAssetGRO;
    private String fob;
    private String permitNumber;
    private MasterItem status;
    private MasterItem masterAgent;
    private Projreport_Template templateid;
    private boolean favourite;
    private boolean isewayexported;
    private String postText;
    GoodsReceiptOrderCustomData goodsReceiptOrderCustomData;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private boolean printed;
    private Tax tax;
    private boolean isOpenInPR;
    private boolean isOpenInPI;
    private double discountinbase;
    private double totalamount;
    private double totalamountinbase;
    private Term term;
    private String challanNumber; // for india country
    private String formtype;//For India Country Only.
    private Boolean termsincludegst; // flag of calculated the GST amount on Basic or on adding other terms amount
    private JournalEntry inventoryJE; // journal entry to be posted if MRP flow is activated
    private boolean gstIncluded;// Flag To  check if Transcation is including GST or Excluding GST
    private String supplierInvoiceNo;//SDP-4510
    private boolean isJobWorkOutOrder;
    private boolean isIndGSTApplied;  //ERP-32829 
    private boolean applyTaxToTerms;
    private boolean isRoundingAdjustmentApplied;
    private double roundingadjustmentamount;
    private double roundingadjustmentamountinbase;
    private boolean isMerchantExporter;//For India Country Only.
    
    public boolean isIsRoundingAdjustmentApplied() {
        return isRoundingAdjustmentApplied;
    }

    public void setIsRoundingAdjustmentApplied(boolean isRoundingAdjustmentApplied) {
        this.isRoundingAdjustmentApplied = isRoundingAdjustmentApplied;
    }

    public double getRoundingadjustmentamount() {
        return roundingadjustmentamount;
    }

    public void setRoundingadjustmentamount(double roundingadjustmentamount) {
        this.roundingadjustmentamount = roundingadjustmentamount;
    }

    public double getRoundingadjustmentamountinbase() {
        return roundingadjustmentamountinbase;
    }

    public void setRoundingadjustmentamountinbase(double roundingadjustmentamountinbase) {
        this.roundingadjustmentamountinbase = roundingadjustmentamountinbase;
    }

    public boolean isIsewayexported() {
        return isewayexported;
    }

    public void setIsewayexported(boolean isewayexported) {
        this.isewayexported = isewayexported;
    }
    
        
    public boolean isIsIndGSTApplied() {
        return isIndGSTApplied;
    }

    public void setIsIndGSTApplied(boolean isIndGSTApplied) {
        this.isIndGSTApplied = isIndGSTApplied;
    }
    public boolean isIsJobWorkOutOrder() {
        return isJobWorkOutOrder;
    }

    public void setIsJobWorkOutOrder(boolean isJobWorkOutOrder) {
        this.isJobWorkOutOrder = isJobWorkOutOrder;
    }

    public boolean isGstIncluded() {
        return gstIncluded;
    }

    public void setGstIncluded(boolean gstIncluded) {
        this.gstIncluded = gstIncluded;
    }
    
    public GoodsReceiptOrder() {
        isOpenInPR = true;
        isOpenInPI = true;
    }

    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public boolean isIsOpenInPR() {
        return isOpenInPR;
    }

    public void setIsOpenInPR(boolean isOpenInPR) {
        this.isOpenInPR = isOpenInPR;
    }

    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }
    private KWLCurrency currency;
    private double externalCurrencyRate;
    private int approvestatuslevel;
    private boolean isAutoGeneratedGRO;
    private boolean isconsignment;
    private BillingShippingAddresses billingShippingAddresses;
    private boolean rcmApplicable;//For India Country Only.
    private boolean ewayapplicable;//For India Country Only.    
    
    public BillingShippingAddresses getBillingShippingAddresses() {
        return billingShippingAddresses;
    }

    public void setBillingShippingAddresses(BillingShippingAddresses billingShippingAddresses) {
        this.billingShippingAddresses = billingShippingAddresses;
    }

    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public CostCenter getCostcenter() {
        return costcenter;
    }

    public void setCostcenter(CostCenter costcenter) {
        this.costcenter = costcenter;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public String getGoodsReceiptOrderNumber() {
        return goodsReceiptOrderNumber;
    }

    public void setGoodsReceiptOrderNumber(String goodsReceiptOrderNumber) {
        this.goodsReceiptOrderNumber = goodsReceiptOrderNumber;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Set<GoodsReceiptOrderDetails> getRows() {
        return rows;
    }

    public void setRows(Set<GoodsReceiptOrderDetails> rows) {
        this.rows = rows;
    }

    public String getFob() {
        return fob;
    }

    public void setFob(String fob) {
        this.fob = fob;
    }

    public String getShipvia() {
        return shipvia;
    }

    public void setShipvia(String shipvia) {
        this.shipvia = shipvia;
    }

    public MasterItem getStatus() {
        return status;
    }

    public Date getShipdate() {
        return shipdate;
    }

    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    public void setStatus(MasterItem status) {
        this.status = status;
    }

    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public String getPermitNumber() {
        return permitNumber;
    }

    public void setPermitNumber(String permitNumber) {
        this.permitNumber = permitNumber;
    }

    public String getPostText() {
        return postText;
    }

    public void setPostText(String postText) {
        this.postText = postText;
    }

    public GoodsReceiptOrderCustomData getGoodsReceiptOrderCustomData() {
        return goodsReceiptOrderCustomData;
    }

    public void setGoodsReceiptOrderCustomData(GoodsReceiptOrderCustomData goodsReceiptOrderCustomData) {
        this.goodsReceiptOrderCustomData = goodsReceiptOrderCustomData;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public boolean isFixedAssetGRO() {
        return fixedAssetGRO;
    }

    public void setFixedAssetGRO(boolean fixedAssetGRO) {
        this.fixedAssetGRO = fixedAssetGRO;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }
    public boolean isIsAutoGeneratedGRO() {
        return isAutoGeneratedGRO;
    }

    public void setIsAutoGeneratedGRO(boolean isAutoGeneratedGRO) {
        this.isAutoGeneratedGRO = isAutoGeneratedGRO;
    }

    public boolean isIsconsignment() {
        return isconsignment;
    }

    public void setIsconsignment(boolean isconsignment) {
        this.isconsignment = isconsignment;
    }

    public MasterItem getMasterAgent() {
        return masterAgent;
    }
    public void setMasterAgent(MasterItem masterAgent) {
        this.masterAgent = masterAgent;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }
      public boolean isIsOpenInPI() {
        return isOpenInPI;
    }

    public void setIsOpenInPI(boolean isOpenInPI) {
        this.isOpenInPI = isOpenInPI;
    }
        public double getDiscountinbase() {
        return discountinbase;
    }

    public void setDiscountinbase(double discountinbase) {
        this.discountinbase = discountinbase;
    }

    public double getTotalamount() {
        return totalamount;
    }

    public void setTotalamount(double totalamount) {
        this.totalamount = totalamount;
    }

    public double getTotalamountinbase() {
        return totalamountinbase;
    }

    public void setTotalamountinbase(double totalamountinbase) {
        this.totalamountinbase = totalamountinbase;
    }
    public Term getTerm() {
        return term;
    }

    public void setTerm(Term term) {
        this.term = term;
    }
    
    public Boolean getTermsincludegst() {
        return termsincludegst;
    }

    public void setTermsincludegst(Boolean termsincludegst) {
        this.termsincludegst = termsincludegst;
    }

    public JournalEntry getInventoryJE() {
        return inventoryJE;
}

    public void setInventoryJE(JournalEntry inventoryJE) {
        this.inventoryJE = inventoryJE;
    }

    public String getChallanNumber() {
        return challanNumber;
    }

    public void setChallanNumber(String challanNumber) {
        this.challanNumber = challanNumber;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }
    public String getFormtype() {
        return formtype;
    }
    public void setFormtype(String formtype) {
        this.formtype = formtype;
    }

    public String getSupplierInvoiceNo() {
        return supplierInvoiceNo;
    }

    public void setSupplierInvoiceNo(String supplierInvoiceNo) {
        this.supplierInvoiceNo = supplierInvoiceNo;
    }

    public boolean isApplyTaxToTerms() {
        return applyTaxToTerms;
    }

    public void setApplyTaxToTerms(boolean applyTaxToTerms) {
        this.applyTaxToTerms = applyTaxToTerms;
    }

    public boolean isRcmApplicable() {
        return rcmApplicable;
    }

    public void setRcmApplicable(boolean rcmApplicable) {
        this.rcmApplicable = rcmApplicable;
    }

    public boolean isIsMerchantExporter() {
        return isMerchantExporter;
    }

    public void setIsMerchantExporter(boolean isMerchantExporter) {
        this.isMerchantExporter = isMerchantExporter;
    }
    
    public boolean isEwayapplicable() {
        return ewayapplicable;
    }

    public void setEwayapplicable(boolean ewayapplicable) {
        this.ewayapplicable = ewayapplicable;
    }
    
}
