/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import com.krawler.hql.accounting.MasterItem;
import com.krawler.hql.accounting.Vendor;
import java.util.Date;
import java.util.Set;

public class PurchaseReturn {

    private String ID;
    private String purchaseReturnNumber;
    private boolean autoGenerated;
    private Date orderDate;
    private Date shipdate;
    private Vendor vendor;
    private String memo;
    private Set<PurchaseReturnDetail> rows;
    private Company company;
    private boolean deleted;
    private CostCenter costcenter;
    private String shipvia;
    private double externalCurrencyRate;
    private String fob;
    private MasterItem status;
    private Projreport_Template templateid;
    private boolean favourite;
    private boolean printed;
    private String postText;
    private PurchaseReturnCustomData purchaseReturnCustomData;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private KWLCurrency currency;
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private boolean isNoteAlso;
    private boolean isewayexported;
    private boolean isconsignment;
    private boolean isdeletable;
    private boolean fixedAsset;
    private boolean gstIncluded; // Flag To  check if Transcation is including GST or Excluding GST
    private boolean applyTaxToTerms;
    private Tax tax;
    private double totalamount;
    private double totalamountinbase;
    private double discountinbase;
    private double totallineleveldiscount;
    private JournalEntry inventoryJE; // journal entry to be posted if MRP flow is activated
    private String formtype;//For India Country Only.
    private String supplierInvoiceNo;//SDP-4510 : Supplier Reference No in AP documents
    private String mvatTransactionNo; //ERP-31738 :Tagging of MVAT Transaction Code to Purchase Return & DN to Vendor
    private boolean isIndGSTApplied;  // ERP-32829 
    private boolean ewayapplicable;
        
    public boolean isIsIndGSTApplied() {
        return isIndGSTApplied;
    }

    public void setIsIndGSTApplied(boolean isIndGSTApplied) {
        this.isIndGSTApplied = isIndGSTApplied;
    }    
    public PurchaseReturn() {
        this.isdeletable = true; // isdeletebale default should be true as first time it allow to delete and later on we will check if used to deliver stock againg then we will not allow
    }
    
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public double getTotalamount() {
        return totalamount;
    }

    public void setTotalamount(double totalamount) {
        this.totalamount = totalamount;
    }

    public boolean isIsewayexported() {
        return isewayexported;
    }

    public void setIsewayexported(boolean isewayexported) {
        this.isewayexported = isewayexported;
    }

    
    public double getTotalamountinbase() {
        return totalamountinbase;
    }

    public void setTotalamountinbase(double totalamountinbase) {
        this.totalamountinbase = totalamountinbase;
    }

    public double getDiscountinbase() {
        return discountinbase;
    }

    public void setDiscountinbase(double discountinbase) {
        this.discountinbase = discountinbase;
    }

    public double getTotallineleveldiscount() {
        return totallineleveldiscount;
    }

    public void setTotallineleveldiscount(double totallineleveldiscount) {
        this.totallineleveldiscount = totallineleveldiscount;
    }
    
    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }
    
    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public CostCenter getCostcenter() {
        return costcenter;
    }

    public void setCostcenter(CostCenter costcenter) {
        this.costcenter = costcenter;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }
    
    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }    

    public String getFob() {
        return fob;
    }

    public void setFob(String fob) {
        this.fob = fob;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Set<PurchaseReturnDetail> getRows() {
        return rows;
    }

    public void setRows(Set<PurchaseReturnDetail> rows) {
        this.rows = rows;
    }

    public Date getShipdate() {
        return shipdate;
    }

    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    public String getShipvia() {
        return shipvia;
    }

    public void setShipvia(String shipvia) {
        this.shipvia = shipvia;
    }

    public MasterItem getStatus() {
        return status;
    }

    public void setStatus(MasterItem status) {
        this.status = status;
    }

    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public String getPurchaseReturnNumber() {
        return purchaseReturnNumber;
    }

    public void setPurchaseReturnNumber(String purchaseReturnNumber) {
        this.purchaseReturnNumber = purchaseReturnNumber;
    }

    public String getPostText() {
        return postText;
    }

    public void setPostText(String postText) {
        this.postText = postText;
    }

    public PurchaseReturnCustomData getPurchaseReturnCustomData() {
        return purchaseReturnCustomData;
    }

    public void setPurchaseReturnCustomData(PurchaseReturnCustomData purchaseReturnCustomData) {
        this.purchaseReturnCustomData = purchaseReturnCustomData;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public boolean isIsNoteAlso() {
        return isNoteAlso;
    }

    public void setIsNoteAlso(boolean isNoteAlso) {
        this.isNoteAlso = isNoteAlso;
    }

    public boolean isIsconsignment() {
        return isconsignment;
    }

    public void setIsconsignment(boolean isconsignment) {
        this.isconsignment = isconsignment;
    }

    public boolean isFixedAsset() {
        return fixedAsset;
    }

    public void setFixedAsset(boolean fixedAsset) {
        this.fixedAsset = fixedAsset;
    }

    public boolean isGstIncluded() {
        return gstIncluded;
    }

    public void setGstIncluded(boolean gstIncluded) {
        this.gstIncluded = gstIncluded;
    }

    public boolean isApplyTaxToTerms() {
        return applyTaxToTerms;
    }

    public void setApplyTaxToTerms(boolean applyTaxToTerms) {
        this.applyTaxToTerms = applyTaxToTerms;
    }
    
    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public boolean isIsdeletable() {
        return isdeletable;
    }

    public void setIsdeletable(boolean isdeletable) {
        this.isdeletable = isdeletable;
    }
    
    public JournalEntry getInventoryJE() {
        return inventoryJE;
}

    public void setInventoryJE(JournalEntry inventoryJE) {
        this.inventoryJE = inventoryJE;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }
    public String getFormtype() {
        return formtype;
    }
    public void setFormtype(String formtype) {
        this.formtype = formtype;
    }

    public String getSupplierInvoiceNo() {
        return supplierInvoiceNo;
    }

    public void setSupplierInvoiceNo(String supplierInvoiceNo) {
        this.supplierInvoiceNo = supplierInvoiceNo;
    }

    public String getMvatTransactionNo() {
        return mvatTransactionNo;
    }

    public void setMvatTransactionNo(String mvatTransactionNo) {
        this.mvatTransactionNo = mvatTransactionNo;
    }
    public boolean isEwayapplicable() {
        return ewayapplicable;
    }

    public void setEwayapplicable(boolean ewayapplicable) {
        this.ewayapplicable = ewayapplicable;
    }    
}
