/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.spring.mrp.routingmanagement;

import com.krawler.common.admin.Company;
import com.krawler.common.admin.User;
import com.krawler.hql.accounting.BOMDetail;
import com.krawler.hql.accounting.Product;
import com.krawler.hql.accounting.SequenceFormat;
import com.krawler.spring.mrp.WorkOrder.WorkOrder;
import com.krawler.spring.mrp.workcentremanagement.WorkCentre;
import java.util.Date;
import java.util.Set;

/**
 *
 * @author krawler
 */
public class RoutingTemplate {

    private String id;
    private String routecode;
    private boolean autoGenerated;
    private int seqnumber;//Only to store integer part of sequence format
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private SequenceFormat seqformat;
    private WorkOrder workOrder;
    private boolean isRoutingCode;  // 1= Template 2 = R Code
    private String name;
    private BOMDetail bomid;
    private String projectId;
    private int durationType;
    private int duration;
    private WorkCentre workCenter;
    private Date createdOn;
    private Date updatedOn;
    private Product product;
    private Company company;
    private User createdby;
    private User modifiedby;
     private boolean deleted;
    private Set<RoutingTemplateMachineMapping> machinemapping;
    private Set<RoutingTemplateLabourMapping> labourmapping;
    private RoutingTemplate parentId;
    private RoutingTemplateCustomData accRoutingTemplateCustomData;

    public static final String RTID = "id";
    public static final String PARENTRTID = "parenetid";
    public static final String ALTERNATERTID = "alternateid";
    public static final String ALTERNATEROUTING = "alternaterouting";
    public static final String RTNAME = "routingtname";
    public static final String ALTERNATERTNAME = "alternateroutingtname";
    public static final String RTCODE = "routingtcode";
    public static final String ALTERNATERTCODE = "alternateroutingtcode";
    public static final String BOMID = "bomid";
    public static final String ALTERNATEBOMID = "alternatebomid";
    public static final String BOMNAME = "bomname";
    public static final String ALTERNATEBOMNAME = "alternatebomname";
    public static final String DURATIONTYPE = "durationtype";
    public static final String ALTERNATEDURATIONTYPE = "alternatedurationtype";
    public static final String DURATIONTYPENAME = "durationtypename";
    public static final String ALTERNATEDURATIONTYPENAME = "alternatedurationtypename";

    public static final String DURATION = "duration";
    public static final String ALTERNATEDURATION = "alternateduration";
    public static final String HOURS = "Hours";
    public static final String ALTERNATEHOURS = "alternateHours";
    public static final String DAYS = "Days";
    public static final String ALTERNATEDAYS = "alternateDays";
    public static final String WORKCENTER = "workcenter";
    public static final String ALTERNATEWORKCENTER = "alternateworkcenter";
    public static final String WORKORDER = "workorder";
    public static final String WORKCENTERNAME = "workcentername";
    public static final String ALTERNATEWORKCENTERNAME = "alternateworkcentername";
    
    public static final String USERID = "userid";
    public static final String MODIFIEDBY = "modifiedby";
    public static final String COMPANYID = "companyid";

    public static final String MACHINEMAPPING = "machinemapping";
    public static final String ALTERNATEMACHINEMAPPING = "alternatemachinemapping";
    public static final String LABOURMAPPING = "labourmapping";

    public static final String ALTERNATELABOURMAPPING = "alternatelabourmapping";
    public static final String LABOURID = "labourid";
    public static final String ALTERNATELABOURID = "alternatelabourid";
    public static final String LABOURNAME = "labourname";
    public static final String ALTERNATELABOURNAME = "alternatelabourname";
    public static final String MACHINEID = "machineid";
    public static final String ALTERNATEMACHINEID = "alternatemachineid";
    public static final String MACHINENAME = "machinename";
    public static final String ALTERNATEMACHINENAME = "alternatemachinename";
    public static final String PROJECTID = "projectId";
    public static final String ALTERNATEPROJECTID = "alternateprojectId";
    public static final String CREATEDON = "createdon";
    public static final String UPDATEDON = "updatedon";
    public static final String CUSTOMFIELD = "customfield";
    public static final String ACCROUTINGTEMPLATECUSTOMDATA = "accroutingtemplatecustomdata";
    
    public static final int MASTERTYPE_ROUTING_TEMPLATE=1;
     public static final int MASTERTYPE_ROUTING_CODE=2;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRoutecode() {
        return routecode;
    }

    public void setRoutecode(String routecode) {
        this.routecode = routecode;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }
        public WorkOrder getWorkOrder() {
        return workOrder;
    }

    public void setWorkOrder(WorkOrder workOrder) {
        this.workOrder = workOrder;
    }

    public boolean isIsRoutingCode() {
        return isRoutingCode;
    }

    public void setIsRoutingCode(boolean isRoutingCode) {
        this.isRoutingCode = isRoutingCode;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BOMDetail getBomid() {
        return bomid;
    }

    public void setBomid(BOMDetail bomid) {
        this.bomid = bomid;
    }

    public int getDurationType() {
        return durationType;
    }

    public void setDurationType(int durationType) {
        this.durationType = durationType;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public WorkCentre getWorkCenter() {
        return workCenter;
    }

    public void setWorkCenter(WorkCentre workCenter) {
        this.workCenter = workCenter;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Set<RoutingTemplateMachineMapping> getMachinemapping() {
        return machinemapping;
    }

    public void setMachinemapping(Set<RoutingTemplateMachineMapping> machinemapping) {
        this.machinemapping = machinemapping;
    }

    public Set<RoutingTemplateLabourMapping> getLabourmapping() {
        return labourmapping;
    }

    public void setLabourmapping(Set<RoutingTemplateLabourMapping> labourmapping) {
        this.labourmapping = labourmapping;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public RoutingTemplate getParentId() {
        return parentId;
    }

    public void setParentId(RoutingTemplate parentId) {
        this.parentId = parentId;
    }

    public RoutingTemplateCustomData getAccRoutingTemplateCustomData() {
        return accRoutingTemplateCustomData;
    }

    public void setAccRoutingTemplateCustomData(RoutingTemplateCustomData accRoutingTemplateCustomData) {
        this.accRoutingTemplateCustomData = accRoutingTemplateCustomData;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
    
    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }
}
