/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

/**
 *
 * @author krawler-user
 */
public class DebitNote {

    private String ID;
    private int sequence;
    private String debitNoteNumber;
    private boolean autoGenerated;
    private String memo;
    private JournalEntry journalEntry;
    private Set<DebitNoteDiscount> discounts;
    private Set<DebitNoteDetail> rows;
    private Set<DebitNoteAgainstCustomerGst> rowsGst;
    private Set<DebitNoteTaxEntry> dnTaxEntryDetails;
    private Company company;
    private Tax tax;
    private KWLCurrency currency;
    private double externalCurrencyRate;
    private boolean deleted;
    private Customer customer;//Used when dntype = 4
    private Vendor vendor;
    private boolean otherwise;//true for DN generated otherwise.
    private boolean openflag;//true if otherwise is true and DN is not used against any invoice.      
    private double dnamount;
    private boolean includingGST;
    private double dnamountdue;
    private int dntype;//1 - CN against unpaid invoice, 2 - CN Otherwise, 3 - CN against paid invoice, 4 - DN against customer 6 - DN For overcharge
    private int seqnumber;//Only to store integer part of sequence format
    private boolean isOpeningBalenceDN;// DN created for account opening balance 
    private boolean dNForVendor;// this field is added for opening balance DN. 
    private boolean normalDN;// DN which is not an opening balance DN is normal DN. default value is true.
    private double openingBalanceAmountDue;
    private double openingBalanceBaseAmountDue; // Store amount due in base currency;
    private double originalOpeningBalanceBaseAmount; // Store amount in base currency
    private Date creationDate;// this field is added at 28 March 2014 for getting creation date of DN in case of opening balance DN.for normal DN DN creation date is getting from Journal Entry.
    private double exchangeRateForOpeningTransaction;// this field is added for opening balance DN.in case of base currency its value will be 1;
    private CostCenter costcenter;
    /*
     * @ conversionRateFromCurrencyToBase - before date 30th July 2014
     * exchangeRateForOpeningTransaction field was saving value - base to
     * currency exchange rate so for previous transactions
     * isConversionRateFromCurrencyToBase flag value will be False. But for new
     * Transactions from Date 18th July 2014 isConversionRateFromCurrencyToBase
     * Flag value will be true. and exchangeRateForOpeningTransaction will
     * contain value - Currency to Base exchange rate.
     */
    private boolean conversionRateFromCurrencyToBase;
    private String narration;// this field is added for opening balance DN.
    private Account account;// this field is added for opening balance DN.
    private boolean oldRecord;// cn of type 1 and 3 created before 22 april 2014 are considered as oldrecord. because creation UI of type 1 and 3 has been change.
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private boolean printed;
    private PurchaseReturn purchaseReturn;
    private OpeningBalanceDebitNoteCustomData openingBalanceDebitNoteCustomData;
    private JournalEntryDetail vendorEntry;
    private double dnamountinbase;// to be used for normal dn
    private String revalJeId;  //for maintaing relation between realised JE and CNDN
    
    private BillingShippingAddresses billingShippingAddresses;
    private int approvestatuslevel;//its value vary from 1 to 11. If it is 11 then it not pending approval
    private String supplierInvoiceNo;//SDP-4510 : Supplier Reference No in AP documents
    private int tdsPaidFlag;// To Verify whether TDS is paid or not.
    private String tdsPayment;// If paid then respective TDS Payment id.
    private int tdsInterestPaidFlag;// To Verify whether TDS Interest is paid or not.
    private String tdsInterestPayment;// If paid then respective TDS Interest Payment id.
     private String mvatTransactionNo; //ERP-31738 :Tagging of MVAT Transaction Code to Purchase Return & DN to Vendor        
    private MasterItem salesPerson;     //ERP-28249 Debit note against customer for malaysian country.
    private MasterItem agent;//ERM-778
    private double gstCurrencyRate;//ERP-39555 : Add column to save gst currency rate when base currency other then SGD for singapore country.

    public final static int DEBITNOTE_AGAINST_INVOICE=1;
    public final static int DEBITNOTE_OTHERWISE=2;
    
    public MasterItem getSalesPerson() {
        return salesPerson;
    }

    public void setSalesPerson(MasterItem salesPerson) {
        this.salesPerson = salesPerson;
    }

    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public BillingShippingAddresses getBillingShippingAddresses() {
        return billingShippingAddresses;
    }

    public void setBillingShippingAddresses(BillingShippingAddresses billingShippingAddresses) {
        this.billingShippingAddresses = billingShippingAddresses;
    }

    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public int getDntype() {
        return dntype;
    }

    public void setDntype(int dntype) {
        this.dntype = dntype;
    }

    public double getDnamount() {
        return dnamount;
    }

    public void setDnamount(double dnamount) {
        this.dnamount = dnamount;
    }

    public double getDnamountdue() {
        return dnamountdue;
    }

    public void setDnamountdue(double dnamountdue) {
        this.dnamountdue = dnamountdue;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public String getDebitNoteNumber() {
        return debitNoteNumber;
    }

    public void setDebitNoteNumber(String debitNoteNumber) {
        this.debitNoteNumber = debitNoteNumber;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Set<DebitNoteDiscount> getDiscounts() {
        return discounts;
    }

    public void setDiscounts(Set<DebitNoteDiscount> discounts) {
        this.discounts = discounts;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Set<DebitNoteDetail> getRows() {
        return rows;
    }

    public void setRows(Set<DebitNoteDetail> rows) {
        this.rows = rows;
    }

    public int getSequence() {
        return sequence;
    }

    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public boolean isOtherwise() {
        return otherwise;
    }

    public void setOtherwise(boolean otherwise) {
        this.otherwise = otherwise;
    }

    public boolean isOpenflag() {
        return openflag;
    }

    public void setOpenflag(boolean openflag) {
        this.openflag = openflag;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public double getExchangeRateForOpeningTransaction() {
        return exchangeRateForOpeningTransaction;
    }

    public void setExchangeRateForOpeningTransaction(double exchangeRateForOpeningTransaction) {
        this.exchangeRateForOpeningTransaction = exchangeRateForOpeningTransaction;
    }

    public boolean isConversionRateFromCurrencyToBase() {
        return conversionRateFromCurrencyToBase;
    }

    public void setConversionRateFromCurrencyToBase(boolean conversionRateFromCurrencyToBase) {
        this.conversionRateFromCurrencyToBase = conversionRateFromCurrencyToBase;
    }

    public boolean isIsOpeningBalenceDN() {
        return isOpeningBalenceDN;
    }

    public void setIsOpeningBalenceDN(boolean isOpeningBalenceDN) {
        this.isOpeningBalenceDN = isOpeningBalenceDN;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public boolean isNormalDN() {
        return normalDN;
    }

    public void setNormalDN(boolean normalDN) {
        this.normalDN = normalDN;
    }

    public double getOpeningBalanceAmountDue() {
        return openingBalanceAmountDue;
    }

    public void setOpeningBalanceAmountDue(double openingBalanceAmountDue) {
        this.openingBalanceAmountDue = openingBalanceAmountDue;
    }

    public double getOpeningBalanceBaseAmountDue() {
        return openingBalanceBaseAmountDue;
    }

    public void setOpeningBalanceBaseAmountDue(double openingBalanceBaseAmountDue) {
        this.openingBalanceBaseAmountDue = openingBalanceBaseAmountDue;
    }

    public double getOriginalOpeningBalanceBaseAmount() {
        return originalOpeningBalanceBaseAmount;
    }

    public void setOriginalOpeningBalanceBaseAmount(double originalOpeningBalanceBaseAmount) {
        this.originalOpeningBalanceBaseAmount = originalOpeningBalanceBaseAmount;
    }

    public boolean isdNForVendor() {
        return dNForVendor;
    }

    public void setdNForVendor(boolean dNForVendor) {
        this.dNForVendor = dNForVendor;
    }

    public Set<DebitNoteTaxEntry> getDnTaxEntryDetails() {
        return dnTaxEntryDetails;
    }

    public void setDnTaxEntryDetails(Set<DebitNoteTaxEntry> dnTaxEntryDetails) {
        this.dnTaxEntryDetails = dnTaxEntryDetails;
    }

    public boolean isOldRecord() {
        return oldRecord;
    }

    public void setOldRecord(boolean oldRecord) {
        this.oldRecord = oldRecord;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public CostCenter getCostcenter() {
        return costcenter;
    }

    public void setCostcenter(CostCenter costcenter) {
        this.costcenter = costcenter;
    }

    public PurchaseReturn getPurchaseReturn() {
        return purchaseReturn;
    }

    public void setPurchaseReturn(PurchaseReturn purchaseReturn) {
        this.purchaseReturn = purchaseReturn;
    }

    public OpeningBalanceDebitNoteCustomData getOpeningBalanceDebitNoteCustomData() {
        return openingBalanceDebitNoteCustomData;
    }

    public void setOpeningBalanceDebitNoteCustomData(OpeningBalanceDebitNoteCustomData openingBalanceDebitNoteCustomData) {
        this.openingBalanceDebitNoteCustomData = openingBalanceDebitNoteCustomData;
    }
    public JournalEntryDetail getVendorEntry() {
        return vendorEntry;
    }
    
    public void setVendorEntry(JournalEntryDetail vendorEntry) {
        this.vendorEntry = vendorEntry;
    }

    public double getDnamountinbase() {
        return dnamountinbase;
    }

    public void setDnamountinbase(double dnamountinbase) {
        this.dnamountinbase = dnamountinbase;
    }

    public String getRevalJeId() {
        return revalJeId;
    }

    public void setRevalJeId(String revalJeId) {
        this.revalJeId = revalJeId;
    }

    /**
     * @return the includingGST
     */
    public boolean isIncludingGST() {
        return includingGST;
    }

    /**
     * @param includingGST the includingGST to set
     */
    public void setIncludingGST(boolean includingGST) {
        this.includingGST = includingGST;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }

    /**
     * @return the rowsGst
     */
    public Set<DebitNoteAgainstCustomerGst> getRowsGst() {
        Set<DebitNoteAgainstCustomerGst> tSet = null;
        if (rowsGst != null) {
            tSet = new TreeSet<>();
            // Added set in TreeSet to order data according to Sr no.
            tSet.addAll(rowsGst);
        }
        return tSet;
    }

    /**
     * @param rowsGst the rowsGst to set
     */
    public void setRowsGst(Set<DebitNoteAgainstCustomerGst> rowsGst) {
        this.rowsGst = rowsGst;
    }

    public String getSupplierInvoiceNo() {
        return supplierInvoiceNo;
    }

    public void setSupplierInvoiceNo(String supplierInvoiceNo) {
        this.supplierInvoiceNo = supplierInvoiceNo;
    }

    /**
     * @return the tax
     */
    public Tax getTax() {
        return tax;
    }

    /**
     * @param tax the tax to set
     */
    public void setTax(Tax tax) {
        this.tax = tax;
    }
  
    public int getTdsPaidFlag() {
        return tdsPaidFlag;
    }

    public void setTdsPaidFlag(int tdsPaidFlag) {
        this.tdsPaidFlag = tdsPaidFlag;
    }

    public String getTdsPayment() {
        return tdsPayment;
    }

    public void setTdsPayment(String tdsPayment) {
        this.tdsPayment = tdsPayment;
    }

    public int getTdsInterestPaidFlag() {
        return tdsInterestPaidFlag;
    }

    public void setTdsInterestPaidFlag(int tdsInterestPaidFlag) {
        this.tdsInterestPaidFlag = tdsInterestPaidFlag;
    }

    public String getTdsInterestPayment() {
        return tdsInterestPayment;
    }

    public void setTdsInterestPayment(String tdsInterestPayment) {
        this.tdsInterestPayment = tdsInterestPayment;
    }
    public String getMvatTransactionNo() {
        return mvatTransactionNo;
    }

    public void setMvatTransactionNo(String mvatTransactionNo) {
        this.mvatTransactionNo = mvatTransactionNo;
    }

    public MasterItem getAgent() {
        return agent;
    }

    public void setAgent(MasterItem agent) {
        this.agent = agent;
    }
    
    public double getGstCurrencyRate() {
        return gstCurrencyRate;
    }

    public void setGstCurrencyRate(double gstCurrencyRate) {
        this.gstCurrencyRate = gstCurrencyRate;
    }
    
}
