/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.Company;
import com.krawler.common.admin.KWLCurrency;
import java.util.Set;

/**
 *
 * @author krawler
 */
public class BillingReceipt {

    private String ID;
    private String billingReceiptNumber;
    private boolean autoGenerated;
    private String memo;
    private JournalEntry journalEntry;
    private JournalEntryDetail deposittoJEDetail;
    private double depositAmount;
    private Set<ReceiptDetail> rows;
    private PayDetail payDetail;
    private Company company;
    private boolean deleted;
    private boolean contraentry;
    private double externalCurrencyRate;
    private KWLCurrency currency;
    private int approvallevel;
    private boolean ismanydbcr;//Used for many debit and credit
    private boolean isadvancefromvendor;//Used for advance payment from vendor
    private double bankChargesAmount;
    private double bankInterestAmount;
    private Account bankInterestAccount;
    private Account bankChargesAccount;
    private int receipttype;
    private String vendor;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String revalJeId; //for maintaing relation between realised JE and payment
    private MasterItem receivedFrom;//Used for storing froms whom payment is received.

    public MasterItem getReceivedFrom() {
        return receivedFrom;
    }

    public void setReceivedFrom(MasterItem receivedFrom) {
        this.receivedFrom = receivedFrom;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public int getReceipttype() {
        return receipttype;
    }

    public void setReceipttype(int receipttype) {
        this.receipttype = receipttype;
    }

    public String getVendor() {
        return vendor;
    }

    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    public JournalEntryDetail getDeposittoJEDetail() {
        return deposittoJEDetail;
    }

    public void setDeposittoJEDetail(JournalEntryDetail deposittoJEDetail) {
        this.deposittoJEDetail = deposittoJEDetail;
    }

    public double getDepositAmount() {
        return depositAmount;
    }

    public void setDepositAmount(double depositAmount) {
        this.depositAmount = depositAmount;
    }

    public double getBankChargesAmount() {
        return bankChargesAmount;
    }

    public void setBankChargesAmount(double bankChargesAmount) {
        this.bankChargesAmount = bankChargesAmount;
    }

    public double getBankInterestAmount() {
        return bankInterestAmount;
    }

    public void setBankInterestAmount(double bankInterestAmount) {
        this.bankInterestAmount = bankInterestAmount;
    }

    public Account getBankInterestAccount() {
        return bankInterestAccount;
    }

    public void setBankInterestAccount(Account bankInterestAccount) {
        this.bankInterestAccount = bankInterestAccount;
    }

    public Account getBankChargesAccount() {
        return bankChargesAccount;
    }

    public void setBankChargesAccount(Account bankChargesAccount) {
        this.bankChargesAccount = bankChargesAccount;
    }

    public boolean isIsadvancefromvendor() {
        return isadvancefromvendor;
    }

    public void setIsadvancefromvendor(boolean isadvancefromvendor) {
        this.isadvancefromvendor = isadvancefromvendor;
    }

    public boolean isIsmanydbcr() {
        return ismanydbcr;
    }

    public void setIsmanydbcr(boolean ismanydbcr) {
        this.ismanydbcr = ismanydbcr;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public int getApprovallevel() {
        return approvallevel;
    }

    public void setApprovallevel(int approvallevel) {
        this.approvallevel = approvallevel;
    }

    public String getBillingReceiptNumber() {
        return billingReceiptNumber;
    }

    public void setBillingReceiptNumber(String billingReceiptNumber) {
        this.billingReceiptNumber = billingReceiptNumber;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public boolean isContraentry() {
        return contraentry;
    }

    public void setContraentry(boolean contraentry) {
        this.contraentry = contraentry;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public PayDetail getPayDetail() {
        return payDetail;
    }

    public void setPayDetail(PayDetail payDetail) {
        this.payDetail = payDetail;
    }

    public Set<ReceiptDetail> getRows() {
        return rows;
    }

    public void setRows(Set<ReceiptDetail> rows) {
        this.rows = rows;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public String getRevalJeId() {
        return revalJeId;
    }

    public void setRevalJeId(String revalJeId) {
        this.revalJeId = revalJeId;
    }
}
