/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

/**
 *
 * @author krawler-user
 */
public class CreditNote {

    private String ID;
    private int sequence;
    private String creditNoteNumber;
    private boolean autoGenerated;
    private String memo;
    private JournalEntry journalEntry;
    private Set<CreditNoteDiscount> discounts;
    private Set<CreditNoteDetail> rows;
    private Set<CreditNoteAgainstVendorGst> rowsGst;
    private Set<CreditNoteTaxEntry> cnTaxEntryDetails;
    private Company company;
    private Tax tax;
    private KWLCurrency currency;
    private double externalCurrencyRate;
    private boolean deleted;
    private Customer customer;
    private boolean otherwise;//true for CN generated otherwise.
    private boolean openflag;//true if otherwise is true and CN is not used against any invoice.    
    private double cnamount;
    private double cnamountdue;
    private int cntype;//1 - CN against unpaid invoice, 2 - CN Otherwise, 3 - CN against paid invoice, 4 - CN against vendor
    private Vendor vendor; //Used when cntype = 4
    private boolean isOpeningBalenceCN;// CN created for account opening balance 
    private boolean cNForCustomer;// this field is added for opening balance CN. 
    private boolean normalCN;// CN which is not an opening balance CN is normal CN. default value is true.
    private double openingBalanceAmountDue;
    private double openingBalanceBaseAmountDue; // Store amount due in base currency;
    private double originalOpeningBalanceBaseAmount; // Store amount in base currency
    private Date creationDate;// this field is added at 28 March 2014 for getting creation date of CN in case of opening balance CN.for normal CN CN creation date is getting from Journal Entry.
    private double exchangeRateForOpeningTransaction;// this field is added for opening balance CN.in case of base currency its value will be 1;
    private CostCenter costcenter;
    private double gstCurrencyRate; //ERP-39555 : Add column to save gst currency rate when base currency other then SGD for singapore country.   
    /*
     * @ conversionRateFromCurrencyToBase - before date 30th July 2014
     * exchangeRateForOpeningTransaction field was saving value - base to
     * currency exchange rate so for previous transactions
     * isConversionRateFromCurrencyToBase flag value will be False. But for new
     * Transactions from Date 18th July 2014 isConversionRateFromCurrencyToBase
     * Flag value will be true. and exchangeRateForOpeningTransaction will
     * contain value - Currency to Base exchange rate.
     */
    private boolean conversionRateFromCurrencyToBase;
    private String narration;// this field is added for opening balance CN.
    private Account account;// this field is added for opening balance CN.
    private boolean oldRecord;// cn of type 1 and 3 created before 22 april 2014 are considered as oldrecord. because creation UI of type 1 and 3 has been change.
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private boolean printed;
    private SalesReturn salesReturn;
    private OpeningBalanceCreditNoteCustomData openingBalanceCreditNoteCustomData;
    private JournalEntryDetail customerEntry;
    private double cnamountinbase; // to be used for normal cn
    private MasterItem salesPerson;
    private MasterItem masterAgent;
    private String revalJeId;  //for maintaing relation between realised JE and CNDN
    private BillingShippingAddresses billingShippingAddresses;
    private boolean includingGST;
    private int approvestatuslevel;//its value vary from 1 to 11. If it is 11 then it not pending approval
    private String mvatTransactionNo; //ERP-31738 :Tagging of MVAT Transaction Code to Purchase Return & DN to Vendor
    
    public final static int CREDITNOTE_AGAINST_INVOICE=1;
    public final static int CREDITNOTE_OTHERWISE=2;
    
    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }
    
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    public BillingShippingAddresses getBillingShippingAddresses() {
        return billingShippingAddresses;
    }

    public void setBillingShippingAddresses(BillingShippingAddresses billingShippingAddresses) {
        this.billingShippingAddresses = billingShippingAddresses;
    }
    
    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public int getCntype() {
        return cntype;
    }

    public void setCntype(int cntype) {
        this.cntype = cntype;
    }

    public double getCnamount() {
        return cnamount;
    }

    public void setCnamount(double cnamount) {
        this.cnamount = cnamount;
    }

    public double getCnamountdue() {
        return cnamountdue;
    }

    public void setCnamountdue(double cnamountdue) {
        this.cnamountdue = cnamountdue;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public boolean isOtherwise() {
        return otherwise;
    }

    public void setOtherwise(boolean otherwise) {
        this.otherwise = otherwise;
    }

    public boolean isOpenflag() {
        return openflag;
    }

    public void setOpenflag(boolean openflag) {
        this.openflag = openflag;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public int getSequence() {
        return sequence;
    }

    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    public Set<CreditNoteDetail> getRows() {
        return rows;
    }

    public void setRows(Set<CreditNoteDetail> rows) {
        this.rows = rows;
    }

    public String getCreditNoteNumber() {
        return creditNoteNumber;
    }

    public void setCreditNoteNumber(String creditNoteNumber) {
        this.creditNoteNumber = creditNoteNumber;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Set<CreditNoteDiscount> getDiscounts() {
        return discounts;
    }

    public void setDiscounts(Set<CreditNoteDiscount> discounts) {
        this.discounts = discounts;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public double getExchangeRateForOpeningTransaction() {
        return exchangeRateForOpeningTransaction;
    }

    public void setExchangeRateForOpeningTransaction(double exchangeRateForOpeningTransaction) {
        this.exchangeRateForOpeningTransaction = exchangeRateForOpeningTransaction;
    }

    public boolean isConversionRateFromCurrencyToBase() {
        return conversionRateFromCurrencyToBase;
    }

    public void setConversionRateFromCurrencyToBase(boolean conversionRateFromCurrencyToBase) {
        this.conversionRateFromCurrencyToBase = conversionRateFromCurrencyToBase;
    }

    public boolean isIsOpeningBalenceCN() {
        return isOpeningBalenceCN;
    }

    public void setIsOpeningBalenceCN(boolean isOpeningBalenceCN) {
        this.isOpeningBalenceCN = isOpeningBalenceCN;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public boolean isNormalCN() {
        return normalCN;
    }

    public void setNormalCN(boolean normalCN) {
        this.normalCN = normalCN;
    }

    public double getOpeningBalanceAmountDue() {
        return openingBalanceAmountDue;
    }

    public void setOpeningBalanceAmountDue(double openingBalanceAmountDue) {
        this.openingBalanceAmountDue = openingBalanceAmountDue;
    }

    public double getOpeningBalanceBaseAmountDue() {
        return openingBalanceBaseAmountDue;
    }

    public void setOpeningBalanceBaseAmountDue(double openingBalanceBaseAmountDue) {
        this.openingBalanceBaseAmountDue = openingBalanceBaseAmountDue;
    }

    
    public double getOriginalOpeningBalanceBaseAmount() {
        return originalOpeningBalanceBaseAmount;
    }

    public void setOriginalOpeningBalanceBaseAmount(double originalOpeningBalanceBaseAmount) {
        this.originalOpeningBalanceBaseAmount = originalOpeningBalanceBaseAmount;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public boolean iscNForCustomer() {
        return cNForCustomer;
    }

    public void setcNForCustomer(boolean cNForCustomer) {
        this.cNForCustomer = cNForCustomer;
    }

    public Set<CreditNoteTaxEntry> getCnTaxEntryDetails() {
        return cnTaxEntryDetails;
    }

    public void setCnTaxEntryDetails(Set<CreditNoteTaxEntry> cnTaxEntryDetails) {
        this.cnTaxEntryDetails = cnTaxEntryDetails;
    }

    public boolean isOldRecord() {
        return oldRecord;
    }

    public void setOldRecord(boolean oldRecord) {
        this.oldRecord = oldRecord;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public CostCenter getCostcenter() {
        return costcenter;
    }

    public void setCostcenter(CostCenter costcenter) {
        this.costcenter = costcenter;
    }

    public SalesReturn getSalesReturn() {
        return salesReturn;
    }

    public void setSalesReturn(SalesReturn salesReturn) {
        this.salesReturn = salesReturn;
    }

    public OpeningBalanceCreditNoteCustomData getOpeningBalanceCreditNoteCustomData() {
        return openingBalanceCreditNoteCustomData;
    }

    public void setOpeningBalanceCreditNoteCustomData(OpeningBalanceCreditNoteCustomData openingBalanceCreditNoteCustomData) {
        this.openingBalanceCreditNoteCustomData = openingBalanceCreditNoteCustomData;
    }
    
    public JournalEntryDetail getCustomerEntry() {
        return customerEntry;
    }
    
    public void setCustomerEntry(JournalEntryDetail customerEntry) {
        this.customerEntry = customerEntry;
    }

    public double getCnamountinbase() {
        return cnamountinbase;
    }

    public void setCnamountinbase(double cnamountinbase) {
        this.cnamountinbase = cnamountinbase;
    }

    public MasterItem getSalesPerson() {
        return salesPerson;
    }

    public void setSalesPerson(MasterItem salesPerson) {
        this.salesPerson = salesPerson;
    }

    public String getRevalJeId() {
        return revalJeId;
    }

    public void setRevalJeId(String revalJeId) {
        this.revalJeId = revalJeId;
    }

    /**
     * @return the includingGST
     */
    public boolean isIncludingGST() {
        return includingGST;
    }

    /**
     * @param includingGST the includingGST to set
     */
    public void setIncludingGST(boolean includingGST) {
        this.includingGST = includingGST;
    }

    public MasterItem getMasterAgent() {
        return masterAgent;
    }

    public void setMasterAgent(MasterItem masterAgent) {
        this.masterAgent = masterAgent;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }

    /**
     * @return the rowsGst
     */
    public Set<CreditNoteAgainstVendorGst> getRowsGst() {
        Set<CreditNoteAgainstVendorGst> tSet = null;
        if (rowsGst != null) {
            tSet = new TreeSet<>();
            // Added set in TreeSet to order data according to Sr no.
            tSet.addAll(rowsGst);
        }
        return tSet;
    }

    /**
     * @param rowsGst the rowsGst to set
     */
    public void setRowsGst(Set<CreditNoteAgainstVendorGst> rowsGst) {
        this.rowsGst = rowsGst;
    }

    /**
     * @return the tax
     */
    public Tax getTax() {
        return tax;
    }

    /**
     * @param tax the tax to set
     */
    public void setTax(Tax tax) {
        this.tax = tax;
    }

    public String getMvatTransactionNo() {
        return mvatTransactionNo;
    }

    public void setMvatTransactionNo(String mvatTransactionNo) {
        this.mvatTransactionNo = mvatTransactionNo;
    }
    
    public double getGstCurrencyRate() {
        return gstCurrencyRate;
    }

    public void setGstCurrencyRate(double gstCurrencyRate) {
        this.gstCurrencyRate = gstCurrencyRate;
    }
}
