/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import java.util.Date;
import java.util.Set;

/**
 *
 * @author krawler-user
 */
public class DeliveryOrder {

    private String ID;
    private String deliveryOrderNumber;
    private boolean autoGenerated;
    private Date orderDate;
    private Date shipdate;
    private Customer customer;
    private String memo;
    private String orderNoReferedForMemoAddress; // stores the linked order number whos memo and address we are storing in Do 
    private Set<DeliveryOrderDetail> rows;
    private Set<DOContractMapping> dOContractMappings;
    private Company company;
    private boolean deleted;
    private CostCenter costcenter;
    private String shipvia;
    private String fob;
    private MasterItem status;
    private double externalCurrencyRate;
    private MasterItem salesperson;
    private Projreport_Template templateid;
    private boolean favourite;
    private String postText;
    private String customerPORefNo;
    private DeliveryOrderCustomData deliveryOrderCustomData;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private boolean printed;
    private int approvestatuslevel;
    private JournalEntry journalEntry;
    private boolean fixedAssetDO;
    private boolean leaseDO;// indicates is create DO is Fixed asset Lease DELIVERY order.
    private KWLCurrency currency;
    private boolean isAutoGeneratedDO; // true if DO is generated from invoice side only.
    private boolean isconsignment;
    private boolean isJobWorkOut;  // True for Job Work Records
    private InventoryWarehouse custWarehouse;
    private MasterItem MovementType;
    private boolean appliedForTax;// in case of Malasian company if DO is applied for tax
    private MasterItem driver;
    private BillingShippingAddresses billingShippingAddresses;
    private boolean isDOClosed;
    private boolean POSDO; // Is Invoice generated from POS App 
    private Tax tax;
    private boolean isOpenInSI; //Flag for SI
    private boolean isOpenInSR; //Flag for SR
    private Term term;
    private Boolean termsincludegst; // flag of calculated the GST amount on Basic or on adding other terms amount
    private boolean isewayexported;
    private String formtype;//For India Country Only.
    private double discountinbase;
    private double totalamount;
    private double totalamountinbase;
    private JournalEntry inventoryJE; // journal entry to be posted if MRP flow is activated    
    private Date appliedDate; // Date when Do is applied for tax.
    private boolean gstIncluded; // Flag To  check if Transcation is including GST or Excluding GST
    private boolean isFreeGift;  // Is Do is Free Gift type
    private JournalEntry freeGiftJE; // JE posted for Free Gift DO
    private boolean isIndGSTApplied;
    private boolean rcmapplicable;//For India Country Only.
    private boolean ewayapplicable;//For India Country Only.
    private boolean applyTaxToTerms;
    private double roundingadjustmentamount;
    private double roundingadjustmentamountinbase;
    private boolean isRoundingAdjustmentApplied;
    private boolean isMerchantExporter;//For India Country Only.
    private int generatedSource;//0=web-application,1=MobileApps,2=POS

    public int getGeneratedSource() {
        return generatedSource;
    }

    public void setGeneratedSource(int generatedSource) {
        this.generatedSource = generatedSource;
    }

    public boolean isIsewayexported() {
        return isewayexported;
    }

    public void setIsewayexported(boolean isewayexported) {
        this.isewayexported = isewayexported;
    }

    
    public boolean isIsRoundingAdjustmentApplied() {
        return isRoundingAdjustmentApplied;
    }
    
    public void setIsRoundingAdjustmentApplied(boolean isRoundingAdjustmentApplied) {
        this.isRoundingAdjustmentApplied = isRoundingAdjustmentApplied;
    }

    public double getRoundingadjustmentamount() {
        return roundingadjustmentamount;
    }

    public void setRoundingadjustmentamount(double roundingadjustmentamount) {
        this.roundingadjustmentamount = roundingadjustmentamount;
    }

    public double getRoundingadjustmentamountinbase() {
        return roundingadjustmentamountinbase;
    }

    public void setRoundingadjustmentamountinbase(double roundingadjustmentamountinbase) {
        this.roundingadjustmentamountinbase = roundingadjustmentamountinbase;
    }
    public boolean isRcmapplicable() {
        return rcmapplicable;
    }

    public void setRcmapplicable(boolean rcmapplicable) {
        this.rcmapplicable = rcmapplicable;
    }
    public boolean isEwayapplicable() {
        return ewayapplicable;
    }

    public void setEwayapplicable(boolean ewayapplicable) {
        this.ewayapplicable = ewayapplicable;
    }
    
    public boolean isIsIndGSTApplied() {
        return isIndGSTApplied;
    }

    public void setIsIndGSTApplied(boolean isIndGSTApplied) {
        this.isIndGSTApplied = isIndGSTApplied;
    }
    public boolean isGstIncluded() {
        return gstIncluded;
    }

    public void setGstIncluded(boolean gstIncluded) {
        this.gstIncluded = gstIncluded;
    }
    
    public boolean isIsOpenInSI() {
        return isOpenInSI;
    }

    public void setIsOpenInSI(boolean isOpenInSI) {
        this.isOpenInSI = isOpenInSI;
    }
  
    
     public DeliveryOrder() {
     
        isOpenInSR=true;
        isOpenInSI=true;
    }
   
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public boolean isIsOpenInSR() {
        return isOpenInSR;
    }

    public void setIsOpenInSR(boolean isOpenInSR) {
        this.isOpenInSR = isOpenInSR;
    }
    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }

    public BillingShippingAddresses getBillingShippingAddresses() {
        return billingShippingAddresses;
    }

    public void setBillingShippingAddresses(BillingShippingAddresses billingShippingAddresses) {
        this.billingShippingAddresses = billingShippingAddresses;
    }
    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getPostText() {
        return postText;
    }

    public void setPostText(String postText) {
        this.postText = postText;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public CostCenter getCostcenter() {
        return costcenter;
    }

    public void setCostcenter(CostCenter costcenter) {
        this.costcenter = costcenter;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public String getDeliveryOrderNumber() {
        return deliveryOrderNumber;
    }

    public void setDeliveryOrderNumber(String deliveryOrderNumber) {
        this.deliveryOrderNumber = deliveryOrderNumber;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getOrderNoReferedForMemoAddress() {
        return orderNoReferedForMemoAddress;
    }

    public void setOrderNoReferedForMemoAddress(String orderNoReferedForMemoAddress) {
        this.orderNoReferedForMemoAddress = orderNoReferedForMemoAddress;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Set<DeliveryOrderDetail> getRows() {
        return rows;
    }

    public void setRows(Set<DeliveryOrderDetail> rows) {
        this.rows = rows;
    }

    public String getFob() {
        return fob;
    }

    public void setFob(String fob) {
        this.fob = fob;
    }

    public String getShipvia() {
        return shipvia;
    }

    public void setShipvia(String shipvia) {
        this.shipvia = shipvia;
    }

    public MasterItem getStatus() {
        return status;
    }

    public Date getShipdate() {
        return shipdate;
    }

    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    public void setStatus(MasterItem status) {
        this.status = status;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public String getCustomerPORefNo() {
        return customerPORefNo;
    }

    public void setCustomerPORefNo(String customerPORefNo) {
        this.customerPORefNo = customerPORefNo;
    }
    
    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public DeliveryOrderCustomData getDeliveryOrderCustomData() {
        return deliveryOrderCustomData;
    }

    public void setDeliveryOrderCustomData(DeliveryOrderCustomData deliveryOrderCustomData) {
        this.deliveryOrderCustomData = deliveryOrderCustomData;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }

    public boolean isFixedAssetDO() {
        return fixedAssetDO;
    }

    public void setFixedAssetDO(boolean fixedAssetDO) {
        this.fixedAssetDO = fixedAssetDO;
    }

    public boolean isLeaseDO() {
        return leaseDO;
    }

    public void setLeaseDO(boolean leaseDO) {
        this.leaseDO = leaseDO;
    }

    public Set<DOContractMapping> getdOContractMappings() {
        return dOContractMappings;
    }

    public void setdOContractMappings(Set<DOContractMapping> dOContractMappings) {
        this.dOContractMappings = dOContractMappings;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public boolean isIsAutoGeneratedDO() {
        return isAutoGeneratedDO;
    }

    public void setIsAutoGeneratedDO(boolean isAutoGeneratedDO) {
        this.isAutoGeneratedDO = isAutoGeneratedDO;
    }

    public boolean isIsconsignment() {
        return isconsignment;
    }

    public void setIsconsignment(boolean isconsignment) {
        this.isconsignment = isconsignment;
    }

    public InventoryWarehouse getCustWarehouse() {
        return custWarehouse;
    }

    public void setCustWarehouse(InventoryWarehouse custWarehouse) {
        this.custWarehouse = custWarehouse;
    }

    public boolean isAppliedForTax() {
        return appliedForTax;
    }

    public void setAppliedForTax(boolean appliedForTax) {
        this.appliedForTax = appliedForTax;
    }

    public MasterItem getDriver() {
        return driver;
    }

    public void setDriver(MasterItem driver) {
        this.driver = driver;
    }

    public MasterItem getMovementType() {
        return MovementType;
    }

    public void setMovementType(MasterItem MovementType) {
        this.MovementType = MovementType;
    }

    public boolean isIsDOClosed() {
        return isDOClosed;
    }

    public void setIsDOClosed(boolean isDOClosed) {
        this.isDOClosed = isDOClosed;
    }
    
    public MasterItem getSalesperson() {
        return salesperson;
    }

    public void setSalesperson(MasterItem salesperson) {
        this.salesperson = salesperson;
    }

    public boolean isPOSDO() {
        return POSDO;
    }

    public void setPOSDO(boolean POSDO) {
        this.POSDO = POSDO;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }
        public double getDiscountinbase() {
        return discountinbase;
    }

    public void setDiscountinbase(double discountinbase) {
        this.discountinbase = discountinbase;
    }

    public double getTotalamount() {
        return totalamount;
    }

    public void setTotalamount(double totalamount) {
        this.totalamount = totalamount;
    }

    public double getTotalamountinbase() {
        return totalamountinbase;
    }

    public void setTotalamountinbase(double totalamountinbase) {
        this.totalamountinbase = totalamountinbase;
    }
    
    public Term getTerm() {
        return term;
    }

    public void setTerm(Term term) {
        this.term = term;
    }
    
    public Boolean getTermsincludegst() {
        return termsincludegst;
    }

    public void setTermsincludegst(Boolean termsincludegst) {
        this.termsincludegst = termsincludegst;
    }

    public JournalEntry getInventoryJE() {
        return inventoryJE;
}

    public void setInventoryJE(JournalEntry inventoryJE) {
        this.inventoryJE = inventoryJE;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }

    public boolean isIsJobWorkOut() {
        return isJobWorkOut;
    }

    public void setIsJobWorkOut(boolean isJobWorkOut) {
        this.isJobWorkOut = isJobWorkOut;
    }
    public String getFormtype() {
        return formtype;
    }
    public void setFormtype(String formtype) {
        this.formtype = formtype;
    }
    public Date getAppliedDate() {
        return appliedDate;
    }

    public void setAppliedDate(Date appliedDate) {
        this.appliedDate = appliedDate;
    }

    public boolean isIsFreeGift() {
        return isFreeGift;
    }

    public void setIsFreeGift(boolean isFreeGift) {
        this.isFreeGift = isFreeGift;
    }

    public JournalEntry getFreeGiftJE() {
        return freeGiftJE;
    }

    public void setFreeGiftJE(JournalEntry freeGiftJE) {
        this.freeGiftJE = freeGiftJE;
    }

    public boolean isApplyTaxToTerms() {
        return applyTaxToTerms;
    }

    public void setApplyTaxToTerms(boolean applyTaxToTerms) {
        this.applyTaxToTerms = applyTaxToTerms;
    }

    public boolean isIsMerchantExporter() {
        return isMerchantExporter;
    }

    public void setIsMerchantExporter(boolean isMerchantExporter) {
        this.isMerchantExporter = isMerchantExporter;
    }
        
}
