/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

/**
 *
 * @author krawler-user
 */
public class Invoice {

    private String ID;
    private String invoiceNumber;
    private boolean autoGenerated;
    private String billTo;
    private String shipTo;
    private Date dueDate;
    private Date shipDate;
    private String memo;
    private Discount discount;
    private JournalEntry journalEntry;
    private Set<InvoiceDetail> rows;
    private Set<InvoiceContractMapping> contractMappings;
    private JournalEntryDetail customerEntry;
    private JournalEntryDetail shipEntry;
    private JournalEntryDetail otherEntry;
    private JournalEntryDetail taxEntry;
    private JournalEntryDetail roundingAdjustmentEntry;
    private Company company;
    private KWLCurrency currency;
    private ExchangeRateDetails exchangeRateDetail;
    private boolean deleted;
    private double externalCurrencyRate;
    private Tax tax;
    private Customer customer;
    private User salesperson;
    private MasterItem masterSalesPerson;
    private Invoice parentInvoice;
    private RepeatedInvoices repeateInvoice;
    private String poRefNumber;
    private boolean partialinv;
    private boolean isjobWorkInvoice;
    private int pendingapproval;
    private String shipvia;
    private String fob;
    private Projreport_Template templateid;
//    private ModuleTemplate moduletemplateid;
    private boolean favourite;
    private boolean fixedAssetInvoice;
    private boolean fixedAssetLeaseInvoice;
    private String inventoryorderid;
    private int approvallevel;
    private User approver;
    private int istemplate;
    private double shiplength;
    private String invoicetype;
    private String postText;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private Term termid;
    private Account account;
    private boolean isOpeningBalenceInvoice;// invoice which is being create from account opening balance button in customer/vendor creation form will have this flag true;
    private boolean normalInvoice;// invoice which is not an opening balance invoice is normal invoice. default value is true.
    private double originalOpeningBalanceAmount;
    private double openingBalanceAmountDue; // Store amount due in invoice currency;
    private double originalOpeningBalanceBaseAmount; // Store amount in base currency
    private double openingBalanceBaseAmountDue; // Store amount due in base currency;
    private double invoiceamountdue; // vallue will be stored in invoice currency 
    private double exchangeRateForOpeningTransaction;// in case of base currency its value will be 1;
    /*
     * @ conversionRateFromCurrencyToBase - before date 30th July 2014
     * exchangeRateForOpeningTransaction field was saving value - base to
     * currency exchange rate so for previous transactions
     * isConversionRateFromCurrencyToBase flag value will be False. But for new
     * Transactions from Date 18th July 2014 isConversionRateFromCurrencyToBase
     * Flag value will be true. and exchangeRateForOpeningTransaction will
     * contain value - Currency to Base exchange rate.
     */
    private boolean conversionRateFromCurrencyToBase;
    private Date poRefDate;
    private Date lastModifiedDate;
    private Date creationDate;// this field is added at 6 March 2014 for getting creation date of invoice in case of opening balance invoice.for normal invoices invoice creation date is getting from Journal Entry.
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private boolean cashtransaction;
    private BillingShippingAddresses billingShippingAddresses;
    private boolean printed;
    private boolean gstIncluded;
    private OpeningBalanceInvoiceCustomData openingBalanceInvoiceCustomData;
    private boolean isconsignment;
    private InventoryWarehouse custWarehouse;
    private MasterItem MovementType; //for maintaning movement warehouse mapping in consignment
    private int badDebtType;// badDebtType == 0 if invoice is not to come in recover tab; badDebtType == 1 if invoice to come in recover tab after claiming it; ==2 if it is recovered
    private int claimedPeriod;// months in number like - 0 for jan
    private Date debtClaimedDate;
//    private Date debtRecoveredDate;
    private String deliveryTime;
    private boolean linkedWithTaxAppliedDO;// for Malasian company
    private PayDetail payDetail;
    private double gstCurrencyRate;//Only used if the country is Singapore and the base currency is not SGD.
    private Boolean termsincludegst; // flag of calculated the GST amount on Basic or on adding other terms amount
    private int approvestatuslevel;
    private boolean draft; // used for drafted invoices
    private boolean POSInvoice; // Is Invoice generated from POS App 
    private boolean isOpenDO; // Is Invoice is used in DO(Delivery order) 
    private boolean isOpenSR; // Is Invoice is used in SR(Sales Return) 
    private boolean isOpenReceipt; // Used when payment done for invoices
    private Date amountDueDate; // used to store the date of transaction on which amountdue of invoice is set to 0.
    private double invoiceamount;
    private double invoiceamountinbase;
    private double invoiceAmountDueInBase; //normal invoice amount due in base
    private double discountAmount;
    private double discountAmountInBase;
    private double claimAmountDue; // ERP-19263 . It is the amount calied for bad debt invoices.
    private boolean isExciseInvoice;
    private String defaultnatureOfPurchase;
    
    private String formtype;//For India Country Only.
    private String excisetype;//For India Country Only.
    private String formseriesno;//For India Country Only.
    private String formno;//For India Country Only.
    private Date formdate;//For India Country Only.
    private double formamount;//For India Country Only.
    private String formstatus;//For India Country Only.
    private int isSupplementary;//For India Country Only.
    private int isexcisepaid;//For India Country Only.
    private boolean rcmapplicable;//For India Country Only.
    private int generatedSource;//0=web-application,1=MobileApps
    private String excisepaidJE;//For India Country Only.
    private double taxamount;  //ERP-27671 - storing tax amount in invoice in invoice currency
    private double excludingGstAmount; //ERP-27671 - storing amount excluding tax in invoice in invoice currency
    private double excludingGstAmountInBase; //ERP-27671 - storing amount excluding tax in invoice in base currency
    private double taxamountinbase;  //ERP-27671 - storing tax amount in invoice in base currency
    private boolean isEmailSent;//flag to update Email Icon
    private MasterItem CustomerBankAccountType; // ERP-29076 - Storing the CustomerBankAccountType
    private boolean isGIROFileGeneratedForUOBBank; // ERP-29076 - wheather GIROfile generated or not
    private PaymentMethod paymentMethodUsedForUOB; // ERP-29076 - Storing the Payment Method by which GIRO is generated
    private boolean isIndGSTApplied;
    private double cashReceived;  //for Cash Received field value from invoice
    private boolean applyTaxToTerms;
    private String exportDeclarationNo;
    private boolean isRoundingAdjustmentApplied;
    private boolean isTaxCommittedOnAvalara;//Flag to indicate whether taxes for invoice have been committed on AvaTax or not. Used when Avalara Integration is enabled.
    private boolean isDropshipDocument;//True ,If DropShip Type SI
    private String defaultPaymentmethod;
    private boolean isMerchantExporter;//For India Country Only.
    private AdditionalMemo additionalmemo;//For Indonesia Country Only. (ID_KETERANGAN_ TAMBAHAN = Additional memo)
    
    public boolean isIsDropshipDocument() {
        return isDropshipDocument;
    }

    public void setIsDropshipDocument(boolean isDropshipDocument) {
        this.isDropshipDocument = isDropshipDocument;
    }

    public boolean isIsTaxCommittedOnAvalara() {
        return isTaxCommittedOnAvalara;
    }

    public void setIsTaxCommittedOnAvalara(boolean isTaxCommittedOnAvalara) {
        this.isTaxCommittedOnAvalara = isTaxCommittedOnAvalara;
    }
    
    public boolean isIsRoundingAdjustmentApplied() {
        return isRoundingAdjustmentApplied;
    }

    public void setIsRoundingAdjustmentApplied(boolean isRoundingAdjustmentApplied) {
        this.isRoundingAdjustmentApplied = isRoundingAdjustmentApplied;
    }

    public JournalEntryDetail getRoundingAdjustmentEntry() {
        return roundingAdjustmentEntry;
    }

    public void setRoundingAdjustmentEntry(JournalEntryDetail roundingAdjustmentEntry) {
        this.roundingAdjustmentEntry = roundingAdjustmentEntry;
    }

    public double getCashReceived() {
        return cashReceived;
    }

    public void setCashReceived(double cashReceived) {
        this.cashReceived = cashReceived;
    }

    public boolean isIsIndGSTApplied() {
        return isIndGSTApplied;
    }

    public void setIsIndGSTApplied(boolean isIndGSTApplied) {
        this.isIndGSTApplied = isIndGSTApplied;
    }

    public int getGeneratedSource() {
        return generatedSource;
    }

    public void setGeneratedSource(int generatedSource) {
        this.generatedSource = generatedSource;
    }
    
    public boolean isIsEmailSent() {
        return isEmailSent;
    }

    public void setIsEmailSent(boolean isEmailSent) {
        this.isEmailSent = isEmailSent;
    }
    public boolean isIsOpenReceipt() {
        return isOpenReceipt;
    }

    public void setIsOpenReceipt(boolean isOpenReceipt) {
        this.isOpenReceipt = isOpenReceipt;
    }
    public int getIsSupplementary() {
        return isSupplementary;
    }

    public void setIsSupplementary(int isSupplementary) {
        this.isSupplementary = isSupplementary;
    }

    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public Date getAmountDueDate() {
        return amountDueDate;
    }

    public void setAmountDueDate(Date amountDueDate) {
        this.amountDueDate = amountDueDate;
    }
    
     public Invoice() {
        this.isOpenDO = true;
        this.isOpenSR = true;
    }
    
    
    public PayDetail getPayDetail() {
        return payDetail;
    }
    public String getdefaultPaymentmethod(){//ERM-735 Associate default payment method for customer
        return defaultPaymentmethod;
    }
    public void setdefaultPaymentmethod(String pmtMethod){
        this.defaultPaymentmethod=pmtMethod;
    }
    public void setPayDetail(PayDetail payDetail) {
        this.payDetail = payDetail;
    }

    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public BillingShippingAddresses getBillingShippingAddresses() {
        return billingShippingAddresses;
    }

    public void setBillingShippingAddresses(BillingShippingAddresses billingShippingAddresses) {
        this.billingShippingAddresses = billingShippingAddresses;
    }

    public boolean isCashtransaction() {
        return cashtransaction;
    }

    public void setCashtransaction(boolean cashtransaction) {
        this.cashtransaction = cashtransaction;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public Term getTermid() {
        return termid;
    }

    public void setTermid(Term termid) {
        this.termid = termid;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getIstemplate() {
        return istemplate;
    }

    public void setIstemplate(int istemplate) {
        this.istemplate = istemplate;
    }

    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public int getApprovallevel() {
        return approvallevel;
    }

    public void setApprovallevel(int approvallevel) {
        this.approvallevel = approvallevel;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public Discount getDiscount() {
        return discount;
    }

    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getShipTo() {
        return shipTo;
    }

    public void setShipTo(String shipTo) {
        this.shipTo = shipTo;
    }

    public Set<InvoiceDetail> getRows() {
        Set<InvoiceDetail> tSet = null;
        if (rows != null) {
            tSet = new TreeSet<>();//Added set in TreeSet to order data according to Sr No.
            tSet.addAll(rows);
        }
        return tSet;
    }

    public void setRows(Set<InvoiceDetail> rows) {
        this.rows = rows;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Date getShipDate() {
        return shipDate;
    }

    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public JournalEntryDetail getCustomerEntry() {
        return customerEntry;
    }

    public void setCustomerEntry(JournalEntryDetail customerEntry) {
        this.customerEntry = customerEntry;
    }

    public JournalEntryDetail getOtherEntry() {
        return otherEntry;
    }

    public void setOtherEntry(JournalEntryDetail otherEntry) {
        this.otherEntry = otherEntry;
    }

    public JournalEntryDetail getShipEntry() {
        return shipEntry;
    }

    public void setShipEntry(JournalEntryDetail shipEntry) {
        this.shipEntry = shipEntry;
    }

    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }

    public JournalEntryDetail getTaxEntry() {
        return taxEntry;
    }

    public void setTaxEntry(JournalEntryDetail taxEntry) {
        this.taxEntry = taxEntry;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public ExchangeRateDetails getExchangeRateDetail() {
        return exchangeRateDetail;
    }

    public void setExchangeRateDetail(ExchangeRateDetails exchangeRateDetail) {
        this.exchangeRateDetail = exchangeRateDetail;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Invoice getParentInvoice() {
        return parentInvoice;
    }

    public void setParentInvoice(Invoice parentInvoice) {
        this.parentInvoice = parentInvoice;
    }

    public RepeatedInvoices getRepeateInvoice() {
        return repeateInvoice;
    }

    public void setRepeateInvoice(RepeatedInvoices repeateInvoice) {
        this.repeateInvoice = repeateInvoice;
    }

    public String getPoRefNumber() {
        return poRefNumber;
    }

    public void setPoRefNumber(String poRefNumber) {
        this.poRefNumber = poRefNumber;
    }

    public boolean isPartialinv() {
        return partialinv;
    }

    public void setPartialinv(boolean partialinv) {
        this.partialinv = partialinv;
    }

    public int getPendingapproval() {
        return pendingapproval;
    }

    public void setPendingapproval(int pendingapproval) {
        this.pendingapproval = pendingapproval;
    }

    public String getFob() {
        return fob;
    }

    public void setFob(String fob) {
        this.fob = fob;
    }

    public String getShipvia() {
        return shipvia;
    }

    public void setShipvia(String shipvia) {
        this.shipvia = shipvia;
    }

    public User getSalesperson() {
        return salesperson;
    }

    public void setSalesperson(User salesperson) {
        this.salesperson = salesperson;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public boolean isFixedAssetInvoice() {
        return fixedAssetInvoice;
    }

    public void setFixedAssetInvoice(boolean fixedAssetInvoice) {
        this.fixedAssetInvoice = fixedAssetInvoice;
    }

    public boolean isFixedAssetLeaseInvoice() {
        return fixedAssetLeaseInvoice;
    }

    public void setFixedAssetLeaseInvoice(boolean fixedAssetLeaseInvoice) {
        this.fixedAssetLeaseInvoice = fixedAssetLeaseInvoice;
    }

    public String getInventoryorderid() {
        return inventoryorderid;
    }

    public void setInventoryorderid(String inventoryorderid) {
        this.inventoryorderid = inventoryorderid;
    }

    public User getApprover() {
        return approver;
    }

    public void setApprover(User approver) {
        this.approver = approver;
    }

    public MasterItem getMasterSalesPerson() {
        return masterSalesPerson;
    }

    public void setMasterSalesPerson(MasterItem masterSalesPerson) {
        this.masterSalesPerson = masterSalesPerson;
    }

    public boolean isIsOpeningBalenceInvoice() {
        return isOpeningBalenceInvoice;
    }

    public void setIsOpeningBalenceInvoice(boolean isOpeningBalenceInvoice) {
        this.isOpeningBalenceInvoice = isOpeningBalenceInvoice;
    }

    public double getOpeningBalanceAmountDue() {
        return openingBalanceAmountDue;
    }

    public void setOpeningBalanceAmountDue(double openingBalanceAmountDue) {
        this.openingBalanceAmountDue = openingBalanceAmountDue;
    }

    public double getOpeningBalanceBaseAmountDue() {
        return openingBalanceBaseAmountDue;
    }

    public void setOpeningBalanceBaseAmountDue(double openingBalanceBaseAmountDue) {
        this.openingBalanceBaseAmountDue = openingBalanceBaseAmountDue;
    }

    public double getInvoiceamountdue() {
        return invoiceamountdue;
    }

    public void setInvoiceamountdue(double invoiceamountdue) {
        this.invoiceamountdue = invoiceamountdue;
    }

    public double getOriginalOpeningBalanceAmount() {
        return originalOpeningBalanceAmount;
    }

    public void setOriginalOpeningBalanceAmount(double originalOpeningBalanceAmount) {
        this.originalOpeningBalanceAmount = originalOpeningBalanceAmount;
    }

    public double getOriginalOpeningBalanceBaseAmount() {
        return originalOpeningBalanceBaseAmount;
    }

    public void setOriginalOpeningBalanceBaseAmount(double originalOpeningBalanceBaseAmount) {
        this.originalOpeningBalanceBaseAmount = originalOpeningBalanceBaseAmount;
    }

    public Date getPoRefDate() {
        return poRefDate;
    }

    public void setPoRefDate(Date poRefDate) {
        this.poRefDate = poRefDate;
    }

    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public boolean isNormalInvoice() {
        return normalInvoice;
    }

    public void setNormalInvoice(boolean normalInvoice) {
        this.normalInvoice = normalInvoice;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public double getExchangeRateForOpeningTransaction() {
        return exchangeRateForOpeningTransaction;
    }

    public void setExchangeRateForOpeningTransaction(double exchangeRateForOpeningTransaction) {
        this.exchangeRateForOpeningTransaction = exchangeRateForOpeningTransaction;
    }

    public boolean isConversionRateFromCurrencyToBase() {
        return conversionRateFromCurrencyToBase;
    }

    public void setConversionRateFromCurrencyToBase(boolean conversionRateFromCurrencyToBase) {
        this.conversionRateFromCurrencyToBase = conversionRateFromCurrencyToBase;
    }

    public String getPostText() {
        return postText;
    }

    public void setPostText(String postText) {
        this.postText = postText;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public Set<InvoiceContractMapping> getContractMappings() {
        return contractMappings;
    }

    public void setContractMappings(Set<InvoiceContractMapping> contractMappings) {
        this.contractMappings = contractMappings;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public boolean isGstIncluded() {
        return gstIncluded;
    }

    public void setGstIncluded(boolean gstIncluded) {
        this.gstIncluded = gstIncluded;
    }

    public double getShiplength() {
        return shiplength;
    }

    public void setShiplength(double shiplength) {
        this.shiplength = shiplength;
    }

    public String getInvoicetype() {
        return invoicetype;
    }

    public void setInvoicetype(String invoicetype) {
        this.invoicetype = invoicetype;
    }

    public OpeningBalanceInvoiceCustomData getOpeningBalanceInvoiceCustomData() {
        return openingBalanceInvoiceCustomData;
    }

    public void setOpeningBalanceInvoiceCustomData(OpeningBalanceInvoiceCustomData openingBalanceInvoiceCustomData) {
        this.openingBalanceInvoiceCustomData = openingBalanceInvoiceCustomData;
    }

    public boolean isIsconsignment() {
        return isconsignment;
    }
    
    public void setIsconsignment(boolean isconsignment) {
        this.isconsignment = isconsignment;
    }
    
    public InventoryWarehouse getCustWarehouse() {
        return custWarehouse;
    }

    public void setCustWarehouse(InventoryWarehouse custWarehouse) {
        this.custWarehouse = custWarehouse;
    }

    public int getBadDebtType() {
        return badDebtType;
    }

    public void setBadDebtType(int badDebtType) {
        this.badDebtType = badDebtType;
    }

    public int getClaimedPeriod() {
        return claimedPeriod;
    }

    public void setClaimedPeriod(int claimedPeriod) {
        this.claimedPeriod = claimedPeriod;
    }

    public boolean isLinkedWithTaxAppliedDO() {
        return linkedWithTaxAppliedDO;
    }

    public void setLinkedWithTaxAppliedDO(boolean linkedWithTaxAppliedDO) {
        this.linkedWithTaxAppliedDO = linkedWithTaxAppliedDO;
    }

    public Date getDebtClaimedDate() {
        return debtClaimedDate;
    }

    public void setDebtClaimedDate(Date debtClaimedDate) {
        this.debtClaimedDate = debtClaimedDate;
    }

//    public Date getDebtRecoveredDate() {
//        return debtRecoveredDate;
//    }
//
//    public void setDebtRecoveredDate(Date debtRecoveredDate) {
//        this.debtRecoveredDate = debtRecoveredDate;
//    }

    public String getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime;
    }
public double getGstCurrencyRate() {
        return gstCurrencyRate;
    }

    public void setGstCurrencyRate(double gstCurrencyRate) {
        this.gstCurrencyRate = gstCurrencyRate;
    }

    public Boolean getTermsincludegst() {
        return termsincludegst;
    }

    public void setTermsincludegst(Boolean termsincludegst) {
        this.termsincludegst = termsincludegst;
    }

    public MasterItem getMovementType() {
        return MovementType;
    }

    public void setMovementType(MasterItem MovementType) {
        this.MovementType = MovementType;
    }
    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }
    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }

    public boolean isDraft() {
        return draft;
    }

    public void setDraft(boolean draft) {
        this.draft = draft;
    }

    public boolean isPOSInvoice() {
        return POSInvoice;
    }

    public void setPOSInvoice(boolean POSInvoice) {
        this.POSInvoice = POSInvoice;
    }
    
      public boolean isIsOpenDO() {
        return isOpenDO;
    }

    public void setIsOpenDO(boolean isOpenDO) {
        this.isOpenDO = isOpenDO;
    }

    public boolean isIsOpenSR() {
        return isOpenSR;
    }

    public void setIsOpenSR(boolean isOpenSR) {
        this.isOpenSR = isOpenSR;
    }

    public double getInvoiceamount() {
        return invoiceamount;
    }

    public void setInvoiceamount(double invoiceamount) {
        this.invoiceamount = invoiceamount;
    }

    public double getInvoiceamountinbase() {
        return invoiceamountinbase;
    }

    public void setInvoiceamountinbase(double invoiceamountinbase) {
        this.invoiceamountinbase = invoiceamountinbase;
    }

    public double getInvoiceAmountDueInBase() {
        return invoiceAmountDueInBase;
    }

    public void setInvoiceAmountDueInBase(double invoiceAmountDueInBase) {
        this.invoiceAmountDueInBase = invoiceAmountDueInBase;
    }

    public double getDiscountAmount() {
        return discountAmount;
    }

    public void setDiscountAmount(double discountAmount) {
        this.discountAmount = discountAmount;
    }

    public double getDiscountAmountInBase() {
        return discountAmountInBase;
    }

    public void setDiscountAmountInBase(double discountAmountInBase) {
        this.discountAmountInBase = discountAmountInBase;
    }

    public double getClaimAmountDue() {
        return claimAmountDue;
    }

    public void setClaimAmountDue(double claimAmountDue) {
        this.claimAmountDue = claimAmountDue;
    }

    public boolean isIsExciseInvoice() {
        return isExciseInvoice;
    }

    public void setIsExciseInvoice(boolean isExciseInvoice) {
        this.isExciseInvoice = isExciseInvoice;
    }

    public String getDefaultnatureOfPurchase() {
        return defaultnatureOfPurchase;
    }

    public void setDefaultnatureOfPurchase(String defaultnatureOfPurchase) {
        this.defaultnatureOfPurchase = defaultnatureOfPurchase;
    }

    public String getFormtype() {
        return formtype;
    }
    public void setFormtype(String formtype) {
        this.formtype = formtype;
    }
    public String getFormseriesno() {
        return formseriesno;
    }
    public void setFormseriesno(String formseriesno) {
        this.formseriesno = formseriesno;
    }
    public String getFormno() {
        return formno;
    }
    public void setFormno(String formno) {
        this.formno = formno;
    }
    public Date getFormdate() {
        return formdate;
    }
    public void setFormdate(Date formdate) {
        this.formdate = formdate;
    }
    public double getFormamount() {
        return formamount;
    }
    public void setFormamount(double formamount) {
        this.formamount = formamount;
    }
    public String getFormstatus() {
        return formstatus;
    }
    public void setFormstatus(String formstatus) {
        this.formstatus = formstatus;
    }
    public String getExcisetype() {
        return excisetype;
    }
    public void setExcisetype(String excisetype) {
        this.excisetype = excisetype;
    }
    public int getIsexcisepaid() {
        return isexcisepaid;
    }
    public void setIsexcisepaid(int isexcisepaid) {
        this.isexcisepaid = isexcisepaid;
    }

    public boolean isRcmapplicable() {
        return rcmapplicable;
    }

    public void setRcmapplicable(boolean rcmapplicable) {
        this.rcmapplicable = rcmapplicable;
    }

//    public ModuleTemplate getModuletemplateid() {
//        return moduletemplateid;
//    }
//
//    public void setModuletemplateid(ModuleTemplate moduletemplateid) {
//        this.moduletemplateid = moduletemplateid;
//    }

    public String getExcisepaidJE() {
        return excisepaidJE;
    }

    public void setExcisepaidJE(String excisepaidJE) {
        this.excisepaidJE = excisepaidJE;
    }
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }

    /**
     * @return the taxamount
     */
    public double getTaxamount() {
        return taxamount;
    }

    /**
     * @param taxamount the taxamount to set
     */
    public void setTaxamount(double taxamount) {
        this.taxamount = taxamount;
    }

    /**
     * @return the excludingGstAmount
     */
    public double getExcludingGstAmount() {
        return excludingGstAmount;
    }

    /**
     * @param excludingGstAmount the excludingGstAmount to set
     */
    public void setExcludingGstAmount(double excludingGstAmount) {
        this.excludingGstAmount = excludingGstAmount;
    }

    /**
     * @return the excludingGstAmountInBase
     */
    public double getExcludingGstAmountInBase() {
        return excludingGstAmountInBase;
    }

    /**
     * @param excludingGstAmountInBase the excludingGstAmountInBase to set
     */
    public void setExcludingGstAmountInBase(double excludingGstAmountInBase) {
        this.excludingGstAmountInBase = excludingGstAmountInBase;
    }

    /**
     * @return the taxamountinbase
     */
    public double getTaxamountinbase() {
        return taxamountinbase;
    }

    /**
     * @param taxamountinbase the taxamountinbase to set
     */
    public void setTaxamountinbase(double taxamountinbase) {
        this.taxamountinbase = taxamountinbase;
    }

    public MasterItem getCustomerBankAccountType() {
        return CustomerBankAccountType;
    }

    public void setCustomerBankAccountType(MasterItem CustomerBankAccountType) {
        this.CustomerBankAccountType = CustomerBankAccountType;
    }

    public boolean isIsGIROFileGeneratedForUOBBank() {
        return isGIROFileGeneratedForUOBBank;
    }

    public void setIsGIROFileGeneratedForUOBBank(boolean isGIROFileGeneratedForUOBBank) {
        this.isGIROFileGeneratedForUOBBank = isGIROFileGeneratedForUOBBank;
    }

    public PaymentMethod getPaymentMethodUsedForUOB() {
        return paymentMethodUsedForUOB;
    }

    public void setPaymentMethodUsedForUOB(PaymentMethod paymentMethodUsedForUOB) {
        this.paymentMethodUsedForUOB = paymentMethodUsedForUOB;
    }

    public boolean isApplyTaxToTerms() {
        return applyTaxToTerms;
    }

    public void setApplyTaxToTerms(boolean applyTaxToTerms) {
        this.applyTaxToTerms = applyTaxToTerms;
    }

    public String getExportDeclarationNo() {
        return exportDeclarationNo;
    }

    public void setExportDeclarationNo(String exportDeclarationNo) {
        this.exportDeclarationNo = exportDeclarationNo;
    }

    /**
     * @return the isjobWorkInvoice
     */
    public boolean isIsjobWorkInvoice() {
        return isjobWorkInvoice;
    }

    /**
     * @param isjobWorkInvoice the isjobWorkInvoice to set
     */
    public void setIsjobWorkInvoice(boolean isjobWorkInvoice) {
        this.isjobWorkInvoice = isjobWorkInvoice;
    }

    public boolean isIsMerchantExporter() {
        return isMerchantExporter;
    }

    public void setIsMerchantExporter(boolean isMerchantExporter) {
        this.isMerchantExporter = isMerchantExporter;
    }

    public AdditionalMemo getAdditionalmemo() {
        return additionalmemo;
    }
    
    public void setAdditionalmemo(AdditionalMemo additionalmemo) {
        this.additionalmemo = additionalmemo;
    }
}
