/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.Company;
import java.util.Date;
import java.util.Set;

/**
 *
 * @author krawler
 */
public class Packing {
    private String ID;
    private String packNumber;
    private Date packingDate;
    private String memo;
    private String customer;
    private boolean deleted;
    private Set<PackingDetail> rows;
    private Company company;
    private MasterItem status;
    private double totalCost;//Total Shipping Cost received from UPS REST
    private SequenceFormat seqformat;
    private int seqnumber;
    private boolean autoGenerated;
    private boolean shippedWithUPS;//Flag to indicate that shipment has been created on UPS for the record
    private Set<UpsPackageDetails> upsPackageDetails;

    public Set<UpsPackageDetails> getUpsPackageDetails() {
        return upsPackageDetails;
    }

    public void setUpsPackageDetails(Set<UpsPackageDetails> upsPackageDetails) {
        this.upsPackageDetails = upsPackageDetails;
    }

    public boolean isShippedWithUPS() {
        return shippedWithUPS;
    }

    public void setShippedWithUPS(boolean shippedWithUPS) {
        this.shippedWithUPS = shippedWithUPS;
    }
    
    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }
    
    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getPackNumber() {
        return packNumber;
    }

    public void setPackNumber(String packNumber) {
        this.packNumber = packNumber;
    }

    public Date getPackingDate() {
        return packingDate;
    }

    public void setPackingDate(Date packingDate) {
        this.packingDate = packingDate;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Set<PackingDetail> getRows() {
        return rows;
    }

    public void setRows(Set<PackingDetail> rows) {
        this.rows = rows;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public MasterItem getStatus() {
        return status;
    }

    public void setStatus(MasterItem status) {
        this.status = status;
    }
    
    public double getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
}