/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.*;
import java.util.Date;
import java.util.Set;

/**
 *
 * @author krawler
 */
public class SalesReturn {

    private String ID;
    private String salesReturnNumber;
    private boolean autoGenerated;
    private Date orderDate;
    private Date shipdate;
    private Customer customer;
    private String memo;
    private Set<SalesReturnDetail> rows;
    private Company company;
    private boolean deleted;
    private CostCenter costcenter;
    private String shipvia;
    private double externalCurrencyRate;
    private String fob;
    private MasterItem status;
    private Projreport_Template templateid;
    private boolean favourite;
    private boolean printed;
    private boolean leaseSalesReturn;// indicates that created SR is Lease Sales Return.
    private String postText;
    private SalesReturnCustomData salesReturnCustomData;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private KWLCurrency currency;
    private Contract contract;
    private long createdon;
    private long updatedon;
    private User createdby;
    private User modifiedby;      
    private boolean isconsignment;
    private boolean isewayexported;
    private InventoryWarehouse custWarehouse;
    private boolean gstIncluded; // Flag To  check if Transcation is including GST or Excluding GST
    private boolean applyTaxToTerms;
    private boolean isNoteAlso;// isNoteAlso flag will be true if you are creating Sale/Purchase Return with Credit/Debit Note also
    private boolean isPayment;
    private MasterItem MovementType;
    private boolean isAssignSRNumberntocn; //
    private boolean fixedAsset;
    private Tax tax;
    private double totalamount;
    private double totalamountinbase;
    private double discountinbase;
    private double totallineleveldiscount;
    private boolean isdeletable;
    private MasterItem salesperson;
    private JournalEntry inventoryJE; // journal entry to be posted if MRP flow is activated
    private String formtype;//For India Country Only.
    private String mvatTransactionNo;//For India Country Only.
    private int generatedSource;//0=web-application,1=MobileApps
    private boolean isIndGSTApplied;
    private boolean isTaxCommittedOnAvalara;//Flag to indicate whether taxes have been committed on AvaTax or not. Used when Avalara Integration is enabled.
    private boolean rcmapplicable;//For India Country Only.
    private boolean ewayapplicable;//For India Country Only.

    public boolean isRcmapplicable() {
        return rcmapplicable;
    }

    public void setRcmapplicable(boolean rcmapplicable) {
        this.rcmapplicable = rcmapplicable;
    }
    public boolean isIsTaxCommittedOnAvalara() {
        return isTaxCommittedOnAvalara;
    }

    public void setIsTaxCommittedOnAvalara(boolean isTaxCommittedOnAvalara) {
        this.isTaxCommittedOnAvalara = isTaxCommittedOnAvalara;
    }
    
    public boolean isIsIndGSTApplied() {
        return isIndGSTApplied;
    }

    public void setIsIndGSTApplied(boolean isIndGSTApplied) {
        this.isIndGSTApplied = isIndGSTApplied;
    }
    public int getGeneratedSource() {
        return generatedSource;
    }

    public boolean isIsewayexported() {
        return isewayexported;
    }

    public void setIsewayexported(boolean isewayexported) {
        this.isewayexported = isewayexported;
    }
    
    public void setGeneratedSource(int generatedSource) {
        this.generatedSource = generatedSource;
    }
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public SalesReturn() {
        this.isdeletable = true; // isdeletebale default should be true as first time it allow to delete and later on we will check if used to deliver stock againg then we will not allow
    }

    public double getTotalamount() {
        return totalamount;
    }

    public void setTotalamount(double totalamount) {
        this.totalamount = totalamount;
    }

    public double getTotalamountinbase() {
        return totalamountinbase;
    }

    public void setTotalamountinbase(double totalamountinbase) {
        this.totalamountinbase = totalamountinbase;
    }

    public double getDiscountinbase() {
        return discountinbase;
    }

    public void setDiscountinbase(double discountinbase) {
        this.discountinbase = discountinbase;
    }

    public double getTotallineleveldiscount() {
        return totallineleveldiscount;
    }

    public void setTotallineleveldiscount(double totallineleveldiscount) {
        this.totallineleveldiscount = totallineleveldiscount;
    }

    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }
    public boolean isIsAssignSRNumberntocn() {
        return isAssignSRNumberntocn;
    }

    public void setIsAssignSRNumberntocn(boolean isAssignSRNumberntocn) {
        this.isAssignSRNumberntocn = isAssignSRNumberntocn;
    }
    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public CostCenter getCostcenter() {
        return costcenter;
    }

    public void setCostcenter(CostCenter costcenter) {
        this.costcenter = costcenter;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    } 
    
    public String getFob() {
        return fob;
    }

    public void setFob(String fob) {
        this.fob = fob;
    }

    public String getMemo() {
        return memo;
    }

    public boolean isGstIncluded() {
        return gstIncluded;
    }

    public void setGstIncluded(boolean gstIncluded) {
        this.gstIncluded = gstIncluded;
    }

    public boolean isApplyTaxToTerms() {
        return applyTaxToTerms;
    }

    public void setApplyTaxToTerms(boolean applyTaxToTerms) {
        this.applyTaxToTerms = applyTaxToTerms;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Set<SalesReturnDetail> getRows() {
        return rows;
    }

    public void setRows(Set<SalesReturnDetail> rows) {
        this.rows = rows;
    }

    public String getSalesReturnNumber() {
        return salesReturnNumber;
    }

    public void setSalesReturnNumber(String salesReturnNumber) {
        this.salesReturnNumber = salesReturnNumber;
    }

    public Date getShipdate() {
        return shipdate;
    }

    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    public String getShipvia() {
        return shipvia;
    }

    public void setShipvia(String shipvia) {
        this.shipvia = shipvia;
    }

    public MasterItem getStatus() {
        return status;
    }

    public void setStatus(MasterItem status) {
        this.status = status;
    }

    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public String getPostText() {
        return postText;
    }

    public void setPostText(String postText) {
        this.postText = postText;
    }

    public boolean isLeaseSalesReturn() {
        return leaseSalesReturn;
    }

    public void setLeaseSalesReturn(boolean leaseSalesReturn) {
        this.leaseSalesReturn = leaseSalesReturn;
    }

    public SalesReturnCustomData getSalesReturnCustomData() {
        return salesReturnCustomData;
    }

    public void setSalesReturnCustomData(SalesReturnCustomData salesReturnCustomData) {
        this.salesReturnCustomData = salesReturnCustomData;
    }

    public Contract getContract() {
        return contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public boolean isIsconsignment() {
        return isconsignment;
    }

    public void setIsconsignment(boolean isconsignment) {
        this.isconsignment = isconsignment;
    }

  
    public InventoryWarehouse getCustWarehouse() {
        return custWarehouse;
    }

    public void setCustWarehouse(InventoryWarehouse custWarehouse) {
        this.custWarehouse = custWarehouse;
    }

    public boolean isIsNoteAlso() {
        return isNoteAlso;
    }

    public void setIsNoteAlso(boolean isNoteAlso) {
        this.isNoteAlso = isNoteAlso;
    }

    public MasterItem getMovementType() {
        return MovementType;
    }

    public void setMovementType(MasterItem MovementType) {
        this.MovementType = MovementType;
    }

    public boolean isFixedAsset() {
        return fixedAsset;
    }

    public void setFixedAsset(boolean fixedAsset) {
        this.fixedAsset = fixedAsset;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public boolean isIsdeletable() {
        return isdeletable;
    }

    public void setIsdeletable(boolean isdeletable) {
        this.isdeletable = isdeletable;
    }
    
    public MasterItem getSalesperson() {
        return salesperson;
    }
    
    public void setSalesperson(MasterItem salesperson) {
        this.salesperson = salesperson;
    }
    
    public JournalEntry getInventoryJE() {
        return inventoryJE;
}

    public void setInventoryJE(JournalEntry inventoryJE) {
        this.inventoryJE = inventoryJE;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }
    public String getFormtype() {
        return formtype;
    }
    public void setFormtype(String formtype) {
        this.formtype = formtype;
    }

    public String getMvatTransactionNo() {
        return mvatTransactionNo;
    }

    public void setMvatTransactionNo(String mvatTransactionNo) {
        this.mvatTransactionNo = mvatTransactionNo;
    }

    /**
     * @return the isPayment
     */
    public boolean isIsPayment() {
        return isPayment;
    }

    /**
     * @param isPayment the isPayment to set
     */
    public void setIsPayment(boolean isPayment) {
        this.isPayment = isPayment;
    }
    public boolean isEwayapplicable() {
        return ewayapplicable;
    }

    public void setEwayapplicable(boolean ewayapplicable) {
        this.ewayapplicable = ewayapplicable;
    }    
}
