/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.BillingShippingAddresses;
import java.util.Date;
import java.util.Set;

import com.krawler.common.admin.Company;
import com.krawler.common.admin.KWLCurrency;
import com.krawler.common.admin.Projreport_Template;
import com.krawler.common.admin.User;

/**
 * @author Neeraj
 *
 */
public class Quotation {

    private String ID;
    private String quotationNumber;
    private boolean autoGenerated;
    private Date dueDate;
    private Date quotationDate;
    private Customer customer;
    private String billTo;
    private String shipTo;
    private String memo;
    private Set<QuotationDetail> rows;
    private Company company;
    private boolean deleted;
    private Tax tax;
    private int archieve;
    private boolean perDiscount;
    private double discount;
    private String crmquoteid;
    private Date shipdate;
    private String shipvia;
    private String shippingTerm;
    private String fob;
    private KWLCurrency currency;
    private Projreport_Template templateid;
    private int linkflag; //values are [0,1,2] 0 means Not Linked , 1 means Linked in Customer Invoice, 2 means Linked in Sales Order
    private boolean favourite;
    private boolean leaseQuotation;
    private int quotationType;// quotationType=0 == Normal Quotation; quotationType=1 == Replacement Quotation; quotationType=2 == Maintenance Quotation
    private int istemplate;
    private String postText;
    private QuotationCustomData quotationCustomData;
    private boolean printed;
    private boolean gstIncluded;
    private Contract contract;// it will be save if quotation is created from Product Replacement selection
    private double shiplength;
    private Term term;
    private String invoicetype;
    private String maintenance; // maintenance id of quotation
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private MasterItem salesperson; //sales person name 
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private Date validdate; //Valid Till field for Quotation
    private BillingShippingAddresses billingShippingAddresses;
    private int approvestatuslevel;
    private double externalCurrencyRate;
    private Boolean termsincludegst; // flag of calculated the GST amount on Basic or on adding other terms amount
    private String customerPORefNo;
    private double totalProfitMargin;
    private double totalProfitMarginPercent;
    private boolean isopen;
    private double quotationamount;
    private double quotationamountinbase;
    private double discountinbase;
    private double totallineleveldiscount;
    private boolean draft; // used for drafted quotation -for ewrkz
    private String formtype;
    private boolean isEmailSent;//flag to update Email Icon
    private boolean reserveStockQuantityFlag; //Flag for "Reserve Stock" check box in Quotation Entry Form. There is no impact on any inventory related reports. We only show total reserved qty in Product Master against each product
    private boolean isIndGSTApplied;
    private boolean rcmapplicable;//For India Country Only.
    private boolean applyTaxToTerms;
    private double roundingadjustmentamount;
    private double roundingadjustmentamountinbase;
    private boolean isRoundingAdjustmentApplied;
    private boolean isMerchantExporter;//For India Country Only.

    public boolean isIsRoundingAdjustmentApplied() {
        return isRoundingAdjustmentApplied;
    }

    public void setIsRoundingAdjustmentApplied(boolean isRoundingAdjustmentApplied) {
        this.isRoundingAdjustmentApplied = isRoundingAdjustmentApplied;
    }

    public double getRoundingadjustmentamount() {
        return roundingadjustmentamount;
    }

    public void setRoundingadjustmentamount(double roundingadjustmentamount) {
        this.roundingadjustmentamount = roundingadjustmentamount;
    }

    public double getRoundingadjustmentamountinbase() {
        return roundingadjustmentamountinbase;
    }

    public void setRoundingadjustmentamountinbase(double roundingadjustmentamountinbase) {
        this.roundingadjustmentamountinbase = roundingadjustmentamountinbase;
    }

    

    public boolean isRcmapplicable() {
        return rcmapplicable;
    }

    public void setRcmapplicable(boolean rcmapplicable) {
        this.rcmapplicable = rcmapplicable;
    }

    public boolean isIsIndGSTApplied() {
        return isIndGSTApplied;
    }

    public void setIsIndGSTApplied(boolean isIndGSTApplied) {
        this.isIndGSTApplied = isIndGSTApplied;
    }
    public boolean isReserveStockQuantityFlag() {
        return reserveStockQuantityFlag;
    }

    public void setReserveStockQuantityFlag(boolean reserveStockQuantityFlag) {
        this.reserveStockQuantityFlag = reserveStockQuantityFlag;
    }

    public boolean isIsEmailSent() {
        return isEmailSent;
    }

    public void setIsEmailSent(boolean isEmailSent) {
        this.isEmailSent = isEmailSent;
    }

    public String getFormtype() {
        return formtype;
    }

    public void setFormtype(String formtype) {
        this.formtype = formtype;
    }
    
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public boolean isDraft() {
        return draft;
    }

    public void setDraft(boolean draft) {
        this.draft = draft;
    }
    public double getTotallineleveldiscount() {
        return totallineleveldiscount;
    }

    public void setTotallineleveldiscount(double totallineleveldiscount) {
        this.totallineleveldiscount = totallineleveldiscount;
    }

    public double getQuotationamount() {
        return quotationamount;
    }

    public void setQuotationamount(double quotationamount) {
        this.quotationamount = quotationamount;
    }

    public double getQuotationamountinbase() {
        return quotationamountinbase;
    }

    public void setQuotationamountinbase(double quotationamountinbase) {
        this.quotationamountinbase = quotationamountinbase;
    }

    public double getDiscountinbase() {
        return discountinbase;
    }

    public void setDiscountinbase(double discountinbase) {
        this.discountinbase = discountinbase;
    }
    
    public Quotation() {
        this.isopen=true;
    }
    
    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }
    
    public String getMaintenance() {
        return maintenance;
    }

    public void setMaintenance(String maintenance) {
        this.maintenance = maintenance;
    }

    public String getInvoicetype() {
        return invoicetype;
    }

    public void setInvoicetype(String invoicetype) {
        this.invoicetype = invoicetype;
    }

    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public BillingShippingAddresses getBillingShippingAddresses() {
        return billingShippingAddresses;
    }

    public void setBillingShippingAddresses(BillingShippingAddresses billingShippingAddresses) {
        this.billingShippingAddresses = billingShippingAddresses;
    }

    public Date getValiddate() {
        return validdate;
    }

    public void setValiddate(Date validdate) {
        this.validdate = validdate;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public int getIstemplate() {
        return istemplate;
    }

    public void setIstemplate(int istemplate) {
        this.istemplate = istemplate;
    }

    public boolean isLeaseQuotation() {
        return leaseQuotation;
    }

    public void setLeaseQuotation(boolean leaseQuotation) {
        this.leaseQuotation = leaseQuotation;
    }

    public String getPostText() {
        return postText;
    }

    public void setPostText(String postText) {
        this.postText = postText;
    }

    public boolean isPerDiscount() {
        return perDiscount;
    }

    public void setPerDiscount(boolean perDiscount) {
        this.perDiscount = perDiscount;
    }

    public double getDiscount() {
        return discount;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Date getQuotationDate() {
        return quotationDate;
    }

    public void setQuotationDate(Date quotationDate) {
        this.quotationDate = quotationDate;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Set<QuotationDetail> getRows() {
        return rows;
    }

    public void setRows(Set<QuotationDetail> rows) {
        this.rows = rows;
    }

    public String getquotationNumber() {
        return quotationNumber;
    }

    public void setquotationNumber(String quotationNumber) {
        this.quotationNumber = quotationNumber;
    }

    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }

    public int getArchieve() {
        return archieve;
    }

    public void setArchieve(int archieve) {
        this.archieve = archieve;
    }

    public String getCrmquoteid() {
        return crmquoteid;
    }

    public void setCrmquoteid(String crmquoteid) {
        this.crmquoteid = crmquoteid;
    }

    public Date getShipdate() {
        return shipdate;
    }

    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    public Term getTerm() {
        return term;
    }

    public void setTerm(Term term) {
        this.term = term;
    }

    public String getShippingTerm() {
        return shippingTerm;
    }

    public void setShippingTerm(String shippingTerm) {
        this.shippingTerm = shippingTerm;
    }

    public String getFob() {
        return fob;
    }

    public void setFob(String fob) {
        this.fob = fob;
    }

    public String getShipvia() {
        return shipvia;
    }

    public void setShipvia(String shipvia) {
        this.shipvia = shipvia;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public String getShipTo() {
        return shipTo;
    }

    public void setShipTo(String shipTo) {
        this.shipTo = shipTo;
    }

    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }

    public QuotationCustomData getQuotationCustomData() {
        return quotationCustomData;
    }

    public void setQuotationCustomData(QuotationCustomData quotationCustomData) {
        this.quotationCustomData = quotationCustomData;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public Contract getContract() {
        return contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public MasterItem getSalesperson() {
        return salesperson;
    }

    public void setSalesperson(MasterItem salesperson) {
        this.salesperson = salesperson;
    }

    public boolean isGstIncluded() {
        return gstIncluded;
    }

    public void setGstIncluded(boolean gstIncluded) {
        this.gstIncluded = gstIncluded;
    }

    public double getShiplength() {
        return shiplength;
    }

    public void setShiplength(double shiplength) {
        this.shiplength = shiplength;
    }

    public int getLinkflag() {
        return linkflag;
    }

    public String getQuotationNumber() {
        return quotationNumber;
    }

    public void setQuotationNumber(String quotationNumber) {
        this.quotationNumber = quotationNumber;
    }

    public int getQuotationType() {
        return quotationType;
    }

    public void setQuotationType(int quotationType) {
        this.quotationType = quotationType;
    }

    public void setLinkflag(int linkflag) {
        this.linkflag = linkflag;
    }

    public Boolean getTermsincludegst() {
        return termsincludegst;
    }

    public void setTermsincludegst(Boolean termsincludegst) {
        this.termsincludegst = termsincludegst;
    }

    public String getCustomerPORefNo() {
        return customerPORefNo;
    }

    public void setCustomerPORefNo(String customerPORefNo) {
        this.customerPORefNo = customerPORefNo;
    }

    public double getTotalProfitMargin() {
        return totalProfitMargin;
    }

    public void setTotalProfitMargin(double totalProfitMargin) {
        this.totalProfitMargin = totalProfitMargin;
    }

    public double getTotalProfitMarginPercent() {
        return totalProfitMarginPercent;
    }

    public void setTotalProfitMarginPercent(double totalProfitMarginPercent) {
        this.totalProfitMarginPercent = totalProfitMarginPercent;
    }
    
    public boolean isIsopen() {
        return isopen;
    }

    public void setIsopen(boolean isopen) {
        this.isopen = isopen;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }

    public boolean isApplyTaxToTerms() {
        return applyTaxToTerms;
    }

    public void setApplyTaxToTerms(boolean applyTaxToTerms) {
        this.applyTaxToTerms = applyTaxToTerms;
    }

    public boolean isIsMerchantExporter() {
        return isMerchantExporter;
    }

    public void setIsMerchantExporter(boolean isMerchantExporter) {
        this.isMerchantExporter = isMerchantExporter;
    }
 }
