/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.spring.mrp.jobwork;

import com.krawler.common.admin.Company;
import com.krawler.common.admin.InventoryLocation;
import com.krawler.common.admin.User;
import com.krawler.hql.accounting.Product;
import com.krawler.hql.accounting.SequenceFormat;
import com.krawler.hql.accounting.Vendor;
import com.krawler.spring.mrp.WorkOrder.WorkOrder;
import java.util.Date;

/**
 *
 * @author krawler
 */
public class JobWork {

    private String id;
    private String jobordername;
    private String jobordernumber;
    private SequenceFormat seqformat;
    private Date jobworkdate;
    private Date dateofdelivery;
    private Vendor vendorid;
    private Date dateofshipment;
    private double excisedutychargees;

    private InventoryLocation jobworklocation;
    private String shipmentroute;
    private String gatepass;
    private String otherremarks;
    private Company companyid;
    private User creator;
    private User modifiedby;
    private Product productid;
    private WorkOrder workorderid;

    
    private double productquantity;
    private boolean deleted;

    private int seqnumber;  //Only to store integer part of sequence format

    private boolean autoGenerated; 
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private JobWorkCustomData accJobWorkCustomData;

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }

    public static final String ID = "id";
    public static final String JOBORDERNAME = "jobordername";
    public static final String JOBORDERNUMBER = "jobordernumber";

    public static final String SEQUENCEFORMAT = "seqformat";
    public static final String JOBWORKDATE = "jobworkdate";
    public static final String DATEOFDELIVERY = "dateofdelivery";

    public static final String VENDORID = "vendorid";
    public static final String VENDORCODE = "vendorcode";
    public static final String VENDORNAME = "vendorname";
    public static final String DATEOFSHIPMENT = "dateofshipment";
    public static final String EXCISEDUTYCHARGES = "excisedutychargees";

    public static final String JOBWORKLOCATION = "jobworklocation";
    public static final String JOBWORKLOCATIONID="jobworklocationid";
    public static final String SHIPMENTROUTE = "shipmentroute";
    public static final String GATEPASS = "gatepass";

    public static final String OTHERREMARKS = "otherremarks";
    public static final String COMPANYID = "companyid";
    public static final String USERID = "userid";

    public static final String WORKORDERNAME = "workordername";
    public static final String WORKORDERID = "workorderid";
    public static final String WORKORDERCODE = "workordercode";

    public static final String WORKCENTERNAME = "workcentrename";
    public static final String WORKCENTERID = "workcentreid";
    public static final String WORKCENTERCODE = "workcentrecode";

    public static final String PRODUCTID = "productid";
    public static final String PRODUCTCODE = "productcode";
    public static final String PRODUCTUOMNAME = "uomname";
    public static final String PRODUCTTYPE ="type";
    public static final String PRODUCTQUANTITY = "productquantity";

    public static final String WORKCENTERTYPE = "workcentretype";
    public static final String MACHINEID = "machineid";
    public static final String LABOURID = "labourid";
    public static final String MATERIALID = "materialid";
    public static final String POJONAME = "JobWork";
    public static final String DB_WORKORDERID = "workorderid.ID";
    public static final String CUSTOMFIELD  = "customfield";
    public static final String ACCJOBWORKCUSTOMDATAREF  = "accjobworkcustomdataref";

    public static final String KEY = "name";

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getJobordername() {
        return jobordername;
    }

    public void setJobordername(String jobordername) {
        this.jobordername = jobordername;
    }

    public String getJobordernumber() {
        return jobordernumber;
    }

    public void setJobordernumber(String jobordernumber) {
        this.jobordernumber = jobordernumber;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public Date getJobworkdate() {
        return jobworkdate;
    }

    public void setJobworkdate(Date jobworkdate) {
        this.jobworkdate = jobworkdate;
    }

    public Date getDateofdelivery() {
        return dateofdelivery;
    }

    public void setDateofdelivery(Date dateofdelivery) {
        this.dateofdelivery = dateofdelivery;
    }

    public Vendor getVendorid() {
        return vendorid;
    }

    public void setVendorid(Vendor vendorid) {
        this.vendorid = vendorid;
    }

    public Date getDateofshipment() {
        return dateofshipment;
    }

    public void setDateofshipment(Date dateofshipment) {
        this.dateofshipment = dateofshipment;
    }

    public double getExcisedutychargees() {
        return excisedutychargees;
    }

    public void setExcisedutychargees(double excisedutychargees) {
        this.excisedutychargees = excisedutychargees;
    }
     public InventoryLocation getJobworklocation() {
        return jobworklocation;
    }

    public void setJobworklocation(InventoryLocation jobworklocation) {
        this.jobworklocation = jobworklocation;
    }
    public String getShipmentroute() {
        return shipmentroute;
    }

    public void setShipmentroute(String shipmentroute) {
        this.shipmentroute = shipmentroute;
    }

    public String getGatepass() {
        return gatepass;
    }

    public void setGatepass(String gatepass) {
        this.gatepass = gatepass;
    }

    public String getOtherremarks() {
        return otherremarks;
    }

    public void setOtherremarks(String otherremarks) {
        this.otherremarks = otherremarks;
    }

    public Company getCompanyid() {
        return companyid;
    }

    public void setCompanyid(Company companyid) {
        this.companyid = companyid;
    }

    public User getCreator() {
        return creator;
    }

    public void setCreator(User creator) {
        this.creator = creator;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Product getProductid() {
        return productid;
    }

    public void setProductid(Product productid) {
        this.productid = productid;
    }

    public double getProductquantity() {
        return productquantity;
    }

    public void setProductquantity(double productquantity) {
        this.productquantity = productquantity;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }
     public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
     public WorkOrder getWorkorderid() {
        return workorderid;
    }

    public void setWorkorderid(WorkOrder workorderid) {
        this.workorderid = workorderid;
    }

    public JobWorkCustomData getAccJobWorkCustomData() {
        return accJobWorkCustomData;
    }

    public void setAccJobWorkCustomData(JobWorkCustomData accJobWorkCustomData) {
        this.accJobWorkCustomData = accJobWorkCustomData;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }
}
