/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.Company;
import com.krawler.common.admin.KWLCurrency;
import com.krawler.common.admin.Projreport_Template;
import com.krawler.common.admin.User;
import java.util.Date;
import java.util.Set;

/**
 *
 * @author krawler
 */
public class PurchaseRequisition {

    private String ID;
    private String prNumber;
    private boolean autoGenerated;
    private Date dueDate;
    private Date requisitionDate;
    private Vendor vendor;
    private String memo;
    private Set<PurchaseRequisitionDetail> rows;
    private Company company;
    private User users;
    private boolean deleted;
    private Tax tax;
    private int archieve;
    private int approvestatuslevel;
    private boolean perDiscount;
    private double discount;
    private KWLCurrency currency;
    private Projreport_Template templateid;
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private PurchaseRequisitionCustomData purchaseRequisitionCustomData;
    private boolean favourite;
    private boolean printed;
    private boolean fixedAssetPurchaseRequisition;
    private User createdby;
    private User modifiedby;
    private boolean isDraft;// flag for identify draft
    private boolean isOpenInPO;//Flag for identifying whether Requisition is fully used in PO or not,If fully used then isOpenInPO->false else true
    private Long createdon;
    
    public PurchaseRequisition() {
        isOpenInPO = true;
    }

    public boolean isIsOpenInPO() {
        return isOpenInPO;
    }

    public void setIsOpenInPO(boolean isOpenInPO) {
        this.isOpenInPO = isOpenInPO;
    }

    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }
    
    public boolean isIsDraft() {
        return isDraft;
    }

    public void setIsDraft(boolean isDraft) {
        this.isDraft = isDraft;
    }
    
    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public Projreport_Template getTemplateid() {
        return templateid;
    }

    public void setTemplateid(Projreport_Template templateid) {
        this.templateid = templateid;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }

    public int getArchieve() {
        return archieve;
    }

    public void setArchieve(int archieve) {
        this.archieve = archieve;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public User getUsers() {
        return users;
    }

    public void setUsers(User users) {
        this.users = users;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public double getDiscount() {
        return discount;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public boolean isPerDiscount() {
        return perDiscount;
    }

    public void setPerDiscount(boolean perDiscount) {
        this.perDiscount = perDiscount;
    }

    public String getPrNumber() {
        return prNumber;
    }

    public void setPrNumber(String prNumber) {
        this.prNumber = prNumber;
    }

    public Date getRequisitionDate() {
        return requisitionDate;
    }

    public void setRequisitionDate(Date requisitionDate) {
        this.requisitionDate = requisitionDate;
    }

    public Set<PurchaseRequisitionDetail> getRows() {
        return rows;
    }

    public void setRows(Set<PurchaseRequisitionDetail> rows) {
        this.rows = rows;
    }

    public Tax getTax() {
        return tax;
    }

    public void setTax(Tax tax) {
        this.tax = tax;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public PurchaseRequisitionCustomData getPurchaseRequisitionCustomData() {
        return purchaseRequisitionCustomData;
    }

    public void setPurchaseRequisitionCustomData(PurchaseRequisitionCustomData purchaseRequisitionCustomData) {
        this.purchaseRequisitionCustomData = purchaseRequisitionCustomData;
    }
    
    public boolean isPrinted() {
        return printed;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public boolean isFixedAssetPurchaseRequisition() {
        return fixedAssetPurchaseRequisition;
    }

    public void setFixedAssetPurchaseRequisition(boolean fixedAssetPurchaseRequisition) {
        this.fixedAssetPurchaseRequisition = fixedAssetPurchaseRequisition;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }
    
    public Long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Long createdon) {
        this.createdon = createdon;
    }
}
