/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.krawler.hql.accounting;

import com.krawler.common.admin.Company;
import com.krawler.common.admin.KWLCurrency;
import com.krawler.common.admin.User;
import com.krawler.spring.accounting.vendorpayment.RepeatedPayment;
import com.krawler.utils.json.base.JSONArray;
import java.util.Date;
import java.util.HashMap;
import java.util.Set;

/**
 *
 * @author krawler-user
 */
public class Payment {

    private String ID;
    private String paymentNumber;
    private boolean autoGenerated;
    private String memo;
    private JournalEntry journalEntry;
    private JournalEntryDetail deposittoJEDetail;
    private double depositAmount;
    private Set<PaymentDetail> rows;
    private Set<LinkDetailPayment> linkDetailPayments;
    private Set<AdvanceDetail> advanceDetails;
    private Set<LinkDetailPaymentToAdvancePayment> linkDetailPaymentsToAdvancePayment; // advance payment details link to refund type payment
    private Set<PaymentDetailOtherwise> paymentDetailOtherwises;
    private Set<CreditNotePaymentDetails> creditNotePaymentDetails;
    private PayDetail payDetail;
    private Company company;
    private KWLCurrency currency;
    private double externalCurrencyRate;
    private int receipttype;
    private String customer;
    private boolean deleted;
    private boolean contraentry;
    private boolean nonRefundable;
     private SalesReturn salesReturn;
    private boolean isadvancepayment;
    private boolean ismanydbcr;//Used for many debit and credit
    private Payment advanceid;//Used for advance payment
    private double advanceamount;//Used for advance payment
    private int advanceamounttype;//Used for advance payment
    private double bankChargesAmount;
    private double bankInterestAmount;
    private Account bankInterestAccount;
    private Account bankChargesAccount;
    private boolean GIROFileGenerated;
    private MasterItem paidTo;//Used for storing tos whom payment is done.
    private String revalJeId;  //for maintaing relation between realised JE and payment
    private boolean isOpeningBalencePayment;// Payment created for account opening balance 
    private boolean normalPayment;// Payment which is not an opening balance Payment is normal Payment. default value is true.
    private double openingBalanceAmountDue;// this field is added for opening balance payments.
    private double openingBalanceBaseAmountDue;
    private double originalOpeningBalanceBaseAmount;// stored original amount in base currency which is in "depositAmount" in transaction currency 
    private Date creationDate;// this field is added at 6 March 2014 for getting creation date of Payment in case of opening balance invoice.for normal Payment Payment creation date is getting from Journal Entry.
    private Date chequeDate;// this field is added for opening balance payments.
    private String chequeNumber;// this field is added for opening balance payments.
    private String drawnOn;// this field is added for opening balance payments.
    private Vendor vendor;
    private Account account;// this field is added for opening balance payments.
    private double exchangeRateForOpeningTransaction;// this field is added for opening balance payments, in case of base currency its value will be 1;
    HashMap<String, JSONArray> jcustomarrayMap = new HashMap();
    /*
     * @ conversionRateFromCurrencyToBase - before date 30th July 2014
     * exchangeRateForOpeningTransaction field was saving value - base to
     * currency exchange rate so for previous transactions
     * isConversionRateFromCurrencyToBase flag value will be False. But for new
     * Transactions from Date 18th July 2014 isConversionRateFromCurrencyToBase
     * Flag value will be true. and exchangeRateForOpeningTransaction will
     * contain value - Currency to Base exchange rate.
     */
    private boolean conversionRateFromCurrencyToBase;
    private User createdby;
    private User modifiedby;
    private long createdon;
    private long updatedon;
    private boolean printed;
    private boolean IBGTypeTransaction;
    private IBGReceivingBankDetails ibgreceivingbankdetails;
    private String ibgCode;
    private boolean isCnDnAndInvoicePayment;
    private String cndnAndInvoiceId;//Used for linked cndn payment
    private int invoiceAdvCndnType;//Used for linked cndn payment. 1 - Against Invoice, 2 - Advance Payment, 3- Against CN/DN
    private OpeningBalanceMakePaymentCustomData openingBalanceMakePaymentCustomData;
    private boolean chequeprinted;
    private boolean linkedToClaimedInvoice;
    private int paymentWindowType;//Used differentiate between payment types---payment Against Vendor = 1,payment Against Customer = 2,Aginst GL = 3
    private boolean mainPaymentForCNDNFlag;
    private JournalEntry journalEntryForBankCharges;
    private JournalEntry journalEntryForBankInterest;
    private double paymentcurrencytopaymentmethodcurrencyrate;
    private String payee;
    private String exciseunit;
    private RepeatedPayment repeatedPayment;
    private Payment parentPayment;
    private double depositamountinbase;// to be used for normal payment
    private Set<LinkDetailPaymentToCreditNote> linkDetailPaymentToCreditNote;
    private JournalEntry disHonouredChequeJe;
    private boolean isDishonouredCheque;
    private CIMBReceivingDetails cimbreceivingbankdetails;  // Storing the cimb bank data for GIRo file
    private OCBCReceivingDetails OCBCReceivingDetails;      //To store OCBC bank data for GIRO Generation.
    private int seqnumber;//Only to store integer part of sequence format
    private SequenceFormat seqformat;
    private String datePreffixValue;//Only to store Date Preffix part of sequence format
    private String dateSuffixValue;//Only to store Date Sufefix part of sequence format
    private String dateAfterPreffixValue;//Only to store Date After Prefix part of sequence format
    private int approvestatuslevel;//its value vary from 1 to 11. If it is 11 then it not pending approval
    private String cinNo;
    private JournalEntry importServiceJE;  // SDP-1740. JE posted for payment of import services
    private boolean isEmailSent;//flag to update Email Icon

    /**
     * taxamount is used to store tax amount for india country when RCM is applicable in
     * payment.
     */
    private double taxAmount;
    /**
     * RCM applicable check is used for india country. It is used to apply tax
     * in advance payment.
     */
    private boolean rcmApplicable;
    /**
     * AdvanceToVendor is used for Payment Against GL for India Country.
     */
    private boolean advanceToVendor;
    
    public boolean isIsEmailSent() {
        return isEmailSent;
    }

    public void setIsEmailSent(boolean isEmailSent) {
        this.isEmailSent = isEmailSent;
    }
    public String getDatePreffixValue() {
        return datePreffixValue;
    }

    public void setDatePreffixValue(String datePreffixValue) {
        this.datePreffixValue = datePreffixValue;
    }

    public String getDateSuffixValue() {
        return dateSuffixValue;
    }

    public void setDateSuffixValue(String dateSuffixValue) {
        this.dateSuffixValue = dateSuffixValue;
    }
    
    public String getPayee() {
        return payee;
    }

    public void setPayee(String payee) {
        this.payee = payee;
    }

    public String getExciseunit() {
        return exciseunit;
    }

    public void setExciseunit(String exciseunit) {
        this.exciseunit = exciseunit;
    }
    
    public JournalEntry getJournalEntryForBankInterest() {
        return journalEntryForBankInterest;
    }

    public void setJournalEntryForBankInterest(JournalEntry journalEntryForBankInterest) {
        this.journalEntryForBankInterest = journalEntryForBankInterest;
    }

    public JournalEntry getJournalEntryForBankCharges() {
        return journalEntryForBankCharges;
    }

    public void setJournalEntryForBankCharges(JournalEntry journalEntryForBankCharges) {
        this.journalEntryForBankCharges = journalEntryForBankCharges;
    }

    public boolean isChequeprinted() {
        return chequeprinted;
    }

    public void setChequeprinted(boolean chequeprinted) {
        this.chequeprinted = chequeprinted;
    }
    
    public boolean isPrinted() {
        return printed;
    }

    public boolean isLinkedToClaimedInvoice() {
        return linkedToClaimedInvoice;
    }

    public void setLinkedToClaimedInvoice(boolean linkedToClaimedInvoice) {
        this.linkedToClaimedInvoice = linkedToClaimedInvoice;
    }

    public void setPrinted(boolean printed) {
        this.printed = printed;
    }

    public MasterItem getPaidTo() {
        return paidTo;
    }

    public void setPaidTo(MasterItem paidTo) {
        this.paidTo = paidTo;
    }

    public SequenceFormat getSeqformat() {
        return seqformat;
    }

    public void setSeqformat(SequenceFormat seqformat) {
        this.seqformat = seqformat;
    }

    public boolean isGIROFileGenerated() {
        return GIROFileGenerated;
    }

    public void setGIROFileGenerated(boolean GIROFileGenerated) {
        this.GIROFileGenerated = GIROFileGenerated;
    }

    public int getSeqnumber() {
        return seqnumber;
    }

    public void setSeqnumber(int seqnumber) {
        this.seqnumber = seqnumber;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public JournalEntryDetail getDeposittoJEDetail() {
        return deposittoJEDetail;
    }

    public void setDeposittoJEDetail(JournalEntryDetail deposittoJEDetail) {
        this.deposittoJEDetail = deposittoJEDetail;
    }

    public double getDepositAmount() {
        return depositAmount;
    }

    public void setDepositAmount(double depositAmount) {
        this.depositAmount = depositAmount;
    }

    public boolean isIsmanydbcr() {
        return ismanydbcr;
    }

    public void setIsmanydbcr(boolean ismanydbcr) {
        this.ismanydbcr = ismanydbcr;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public boolean isContraentry() {
        return contraentry;
    }

    public void setContraentry(boolean contraentry) {
        this.contraentry = contraentry;
    }

    public JournalEntry getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(JournalEntry journalEntry) {
        this.journalEntry = journalEntry;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public PayDetail getPayDetail() {
        return payDetail;
    }

    public void setPayDetail(PayDetail payDetail) {
        this.payDetail = payDetail;
    }

    public String getPaymentNumber() {
        return paymentNumber;
    }

    public void setPaymentNumber(String paymentNumber) {
        this.paymentNumber = paymentNumber;
    }

    public Set<PaymentDetail> getRows() {
        return rows;
    }

    public void setRows(Set<PaymentDetail> rows) {
        this.rows = rows;
    }

    public KWLCurrency getCurrency() {
        return currency;
    }

    public void setCurrency(KWLCurrency currency) {
        this.currency = currency;
    }

    public double getExternalCurrencyRate() {
        return externalCurrencyRate;
    }

    public void setExternalCurrencyRate(double externalCurrencyRate) {
        this.externalCurrencyRate = externalCurrencyRate;
    }

    public boolean isIsadvancepayment() {
        return isadvancepayment;
    }

    public void setIsadvancepayment(boolean isadvancepayment) {
        this.isadvancepayment = isadvancepayment;
    }

    public double getAdvanceamount() {
        return advanceamount;
    }

    public void setAdvanceamount(double advanceamount) {
        this.advanceamount = advanceamount;
    }

    public Payment getAdvanceid() {
        return advanceid;
    }

    public void setAdvanceid(Payment advanceid) {
        this.advanceid = advanceid;
    }

    public int getAdvanceamounttype() {
        return advanceamounttype;
    }

    public void setAdvanceamounttype(int advanceamounttype) {
        this.advanceamounttype = advanceamounttype;
    }
    
    public int getReceipttype() {
        return receipttype;
    }

    public void setReceipttype(int receipttype) {
        this.receipttype = receipttype;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public Account getBankChargesAccount() {
        return bankChargesAccount;
    }

    public void setBankChargesAccount(Account bankChargesAccount) {
        this.bankChargesAccount = bankChargesAccount;
    }

    public double getBankChargesAmount() {
        return bankChargesAmount;
    }

    public void setBankChargesAmount(double bankChargesAmount) {
        this.bankChargesAmount = bankChargesAmount;
    }

    public Account getBankInterestAccount() {
        return bankInterestAccount;
    }

    public void setBankInterestAccount(Account bankInterestAccount) {
        this.bankInterestAccount = bankInterestAccount;
    }

    public double getBankInterestAmount() {
        return bankInterestAmount;
    }

    public void setBankInterestAmount(double bankInterestAmount) {
        this.bankInterestAmount = bankInterestAmount;
    }

    public String getRevalJeId() {
        return revalJeId;
    }

    public void setRevalJeId(String revalJeId) {
        this.revalJeId = revalJeId;
    }

    public User getCreatedby() {
        return createdby;
    }

    public void setCreatedby(User createdby) {
        this.createdby = createdby;
    }

    public long getCreatedon() {
        return createdon;
    }

    public void setCreatedon(long createdon) {
        this.createdon = createdon;
    }

    public User getModifiedby() {
        return modifiedby;
    }

    public void setModifiedby(User modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public Date getChequeDate() {
        return chequeDate;
    }

    public void setChequeDate(Date chequeDate) {
        this.chequeDate = chequeDate;
    }

    public String getChequeNumber() {
        return chequeNumber;
    }

    public void setChequeNumber(String chequeNumber) {
        this.chequeNumber = chequeNumber;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getDrawnOn() {
        return drawnOn;
    }

    public void setDrawnOn(String drawnOn) {
        this.drawnOn = drawnOn;
    }

    public double getExchangeRateForOpeningTransaction() {
        return exchangeRateForOpeningTransaction;
    }

    public void setExchangeRateForOpeningTransaction(double exchangeRateForOpeningTransaction) {
        this.exchangeRateForOpeningTransaction = exchangeRateForOpeningTransaction;
    }

    public boolean isConversionRateFromCurrencyToBase() {
        return conversionRateFromCurrencyToBase;
    }

    public void setConversionRateFromCurrencyToBase(boolean conversionRateFromCurrencyToBase) {
        this.conversionRateFromCurrencyToBase = conversionRateFromCurrencyToBase;
    }

    public boolean isIsOpeningBalencePayment() {
        return isOpeningBalencePayment;
    }

    public void setIsOpeningBalencePayment(boolean isOpeningBalencePayment) {
        this.isOpeningBalencePayment = isOpeningBalencePayment;
    }

    public boolean isNormalPayment() {
        return normalPayment;
    }

    public void setNormalPayment(boolean normalPayment) {
        this.normalPayment = normalPayment;
    }

    public double getOpeningBalanceAmountDue() {
        return openingBalanceAmountDue;
    }

    public void setOpeningBalanceAmountDue(double openingBalanceAmountDue) {
        this.openingBalanceAmountDue = openingBalanceAmountDue;
    }

    public double getOpeningBalanceBaseAmountDue() {
        return openingBalanceBaseAmountDue;
    }

    public void setOpeningBalanceBaseAmountDue(double openingBalanceBaseAmountDue) {
        this.openingBalanceBaseAmountDue = openingBalanceBaseAmountDue;
    }

    public double getOriginalOpeningBalanceBaseAmount() {
        return originalOpeningBalanceBaseAmount;
    }

    public void setOriginalOpeningBalanceBaseAmount(double originalOpeningBalanceBaseAmount) {
        this.originalOpeningBalanceBaseAmount = originalOpeningBalanceBaseAmount;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public long getUpdatedon() {
        return updatedon;
    }

    public void setUpdatedon(long updatedon) {
        this.updatedon = updatedon;
    }

    public boolean isIBGTypeTransaction() {
        return IBGTypeTransaction;
    }

    public void setIBGTypeTransaction(boolean IBGTypeTransaction) {
        this.IBGTypeTransaction = IBGTypeTransaction;
    }

    public IBGReceivingBankDetails getIbgreceivingbankdetails() {
        return ibgreceivingbankdetails;
    }

    public void setIbgreceivingbankdetails(IBGReceivingBankDetails ibgreceivingbankdetails) {
        this.ibgreceivingbankdetails = ibgreceivingbankdetails;
    }

    public String getIbgCode() {
        return ibgCode;
    }

    public void setIbgCode(String ibgCode) {
        this.ibgCode = ibgCode;
    }

    public String getCndnAndInvoiceId() {
        return cndnAndInvoiceId;
    }

    public void setCndnAndInvoiceId(String cndnAndInvoiceId) {
        this.cndnAndInvoiceId = cndnAndInvoiceId;
    }

    public boolean isIsCnDnAndInvoicePayment() {
        return isCnDnAndInvoicePayment;
    }

    public void setIsCnDnAndInvoicePayment(boolean isCnDnAndInvoicePayment) {
        this.isCnDnAndInvoicePayment = isCnDnAndInvoicePayment;
    }

    public int getInvoiceAdvCndnType() {
        return invoiceAdvCndnType;
    }

    public void setInvoiceAdvCndnType(int invoiceAdvCndnType) {
        this.invoiceAdvCndnType = invoiceAdvCndnType;
    }

    public OpeningBalanceMakePaymentCustomData getOpeningBalanceMakePaymentCustomData() {
        return openingBalanceMakePaymentCustomData;
    }

    public void setOpeningBalanceMakePaymentCustomData(OpeningBalanceMakePaymentCustomData openingBalanceMakePaymentCustomData) {
        this.openingBalanceMakePaymentCustomData = openingBalanceMakePaymentCustomData;
    }

    public Set<AdvanceDetail> getAdvanceDetails() {
        return advanceDetails;
    }

    public void setAdvanceDetails(Set<AdvanceDetail> advanceDetails) {
        this.advanceDetails = advanceDetails;
    }

    public Set<PaymentDetailOtherwise> getPaymentDetailOtherwises() {
        return paymentDetailOtherwises;
    }

    public void setPaymentDetailOtherwises(Set<PaymentDetailOtherwise> paymentDetailOtherwises) {
        this.paymentDetailOtherwises = paymentDetailOtherwises;
    }

    public Set<LinkDetailPayment> getLinkDetailPayments() {
        return linkDetailPayments;
    }

    public void setLinkDetailPayments(Set<LinkDetailPayment> linkDetailPayments) {
        this.linkDetailPayments = linkDetailPayments;
    }

    public HashMap<String, JSONArray> getJcustomarrayMap() {
        return jcustomarrayMap;
    }

    public void setJcustomarrayMap(HashMap<String, JSONArray> jcustomarrayMap) {
        this.jcustomarrayMap = jcustomarrayMap;
    }

    public int getPaymentWindowType() {
        return paymentWindowType;
    }

    public void setPaymentWindowType(int paymentWindowType) {
        this.paymentWindowType = paymentWindowType;
    }

    public boolean isMainPaymentForCNDNFlag() {
        return mainPaymentForCNDNFlag;
    }

    public void setMainPaymentForCNDNFlag(boolean mainPaymentForCNDNFlag) {
        this.mainPaymentForCNDNFlag = mainPaymentForCNDNFlag;
    }

    public double getPaymentcurrencytopaymentmethodcurrencyrate() {
        return paymentcurrencytopaymentmethodcurrencyrate;
    }

    public void setPaymentcurrencytopaymentmethodcurrencyrate(double paymentcurrencytopaymentmethodcurrencyrate) {
        this.paymentcurrencytopaymentmethodcurrencyrate = paymentcurrencytopaymentmethodcurrencyrate;
    }

    public RepeatedPayment getRepeatedPayment() {
        return repeatedPayment;
    }

    public void setRepeatedPayment(RepeatedPayment repeatedPayment) {
        this.repeatedPayment = repeatedPayment;
    }

    public Payment getParentPayment() {
        return parentPayment;
    }

    public void setParentPayment(Payment parentPayment) {
        this.parentPayment = parentPayment;
    }

    public Set<CreditNotePaymentDetails> getCreditNotePaymentDetails() {
        return creditNotePaymentDetails;
    }

    public void setCreditNotePaymentDetails(Set<CreditNotePaymentDetails> creditNotePaymentDetails) {
        this.creditNotePaymentDetails = creditNotePaymentDetails;
    }

    public double getDepositamountinbase() {
        return depositamountinbase;
    }

    public void setDepositamountinbase(double depositamountinbase) {
        this.depositamountinbase = depositamountinbase;
    }

    public Set<LinkDetailPaymentToCreditNote> getLinkDetailPaymentToCreditNote() {
        return linkDetailPaymentToCreditNote;
    }

    public void setLinkDetailPaymentToCreditNote(Set<LinkDetailPaymentToCreditNote> linkDetailPaymentToCreditNote) {
        this.linkDetailPaymentToCreditNote = linkDetailPaymentToCreditNote;
    }

    public JournalEntry getDisHonouredChequeJe() {
        return disHonouredChequeJe;
    }

    public void setDisHonouredChequeJe(JournalEntry disHonouredChequeJe) {
        this.disHonouredChequeJe = disHonouredChequeJe;
    }

    public boolean isIsDishonouredCheque() {
        return isDishonouredCheque;
    }

    public void setIsDishonouredCheque(boolean isDishonouredCheque) {
        this.isDishonouredCheque = isDishonouredCheque;
    }

    public CIMBReceivingDetails getCimbreceivingbankdetails() {
        return cimbreceivingbankdetails;
    }

    public void setCimbreceivingbankdetails(CIMBReceivingDetails cimbreceivingbankdetails) {
        this.cimbreceivingbankdetails = cimbreceivingbankdetails;
    }

    public OCBCReceivingDetails getOCBCReceivingDetails() {
        return OCBCReceivingDetails;
    }

    public void setOCBCReceivingDetails(OCBCReceivingDetails OCBCReceivingDetails) {
        this.OCBCReceivingDetails = OCBCReceivingDetails;
    }

    /**
     * @return the nonRefundable
     */
    public boolean isNonRefundable() {
        return nonRefundable;
    }

    /**
     * @param nonRefundable the nonRefundable to set
     */
    public void setNonRefundable(boolean nonRefundable) {
        this.nonRefundable = nonRefundable;
    }

    public Set<LinkDetailPaymentToAdvancePayment> getLinkDetailPaymentsToAdvancePayment() {
        return linkDetailPaymentsToAdvancePayment;
    }

    public void setLinkDetailPaymentsToAdvancePayment(Set<LinkDetailPaymentToAdvancePayment> linkDetailPaymentsToAdvancePayment) {
        this.linkDetailPaymentsToAdvancePayment = linkDetailPaymentsToAdvancePayment;
    }
    public String getCinNo() {
        return cinNo;
    }

    public void setCinNo(String cinNo) {
        this.cinNo = cinNo;
    }
    
    /**
     * @return the approvestatuslevel
     */
    public int getApprovestatuslevel() {
        return approvestatuslevel;
    }

    /**
     * @param approvestatuslevel the approvestatuslevel to set
     */
    public void setApprovestatuslevel(int approvestatuslevel) {
        this.approvestatuslevel = approvestatuslevel;
    }
    
    public String getDateAfterPreffixValue() {
        return dateAfterPreffixValue;
    }

    public void setDateAfterPreffixValue(String dateAfterPreffixValue) {
        this.dateAfterPreffixValue = dateAfterPreffixValue;
    }

    public JournalEntry getImportServiceJE() {
        return importServiceJE;
    }

    public void setImportServiceJE(JournalEntry importServiceJE) {
        this.importServiceJE = importServiceJE;
    }
    
    public double getTaxAmount() {
        return taxAmount;
}

    public void setTaxAmount(double taxAmount) {
        this.taxAmount = taxAmount;
    }

    public boolean isRcmApplicable() {
        return rcmApplicable;
    }

    public void setRcmApplicable(boolean rcmApplicable) {
        this.rcmApplicable = rcmApplicable;
    }

    /**
     * @return the salesReturn
     */
    public SalesReturn getSalesReturn() {
        return salesReturn;
    }

    /**
     * @param salesReturn the salesReturn to set
     */
    public void setSalesReturn(SalesReturn salesReturn) {
        this.salesReturn = salesReturn;
    }

    public boolean isAdvanceToVendor() {
        return advanceToVendor;
    }

    public void setAdvanceToVendor(boolean advanceToVendor) {
        this.advanceToVendor = advanceToVendor;
    }
}
